### ISSUE TITLE
Make PDF font size configurable

### ISSUE THREAD

**Issue by plzh** [travs/markdown-pdf#104]
Thanks for the great work! However, the default font size of the body text seems to be too big. May I suggest a default value of e.g., 12pt and, even better, make this configurable.

**Comment by lukehsiao** [comment]
Just as an example of this, when I convert my markdown to PDF, the text is extremely large:

![image](https://cloud.githubusercontent.com/assets/7573542/14261362/175b4434-fa65-11e5-87a7-ff0b177b0697.png)

This image is just a single page of the PDF of the following markdown:

```
We'll do this in four basic steps:
1. Loading raw input data
2. Adding tags and mention-level features
3. Extracting candidate relation mentions
4. Performing distant supervision

### 1.1. Loading raw input data
Our first task is to extract table data from our corpus of PDF datasheets. This is done using our own [table extraction tool](https://github.com/xiao-cheng/table-extraction). This tool outputs TSV values with the schema and sample values like this:

[```]
doc_id     | page_num | table_id | relation | relation_id |           cell_text           | cell_id
-----------+----------+----------+----------+-------------+-------------------------------+--------
112823.pdf |        0 |        0 | row      |          11 | BASE                          |      78
112823.pdf |        0 |        0 | row      |          12 | Rating                        |       7
112823.pdf |        0 |        0 | row      |          12 | Symbol                        |       8
112823.pdf |        0 |        0 | row      |          12 | Value                         |       9
112823.pdf |        0 |        0 | row      |          12 | Unit                          |      56
112823.pdf |        0 |        0 | row      |          13 | Collector - Emitter Voltage   |      10
112823.pdf |        0 |        0 | row      |          13 | VCEO                          |      30
[```]
This is stored into a `table_dump` table in our database. Note that cell-ids are unique only within the scope of a page. For convenience, we have stored the output of the table extraction tool as a TSV file, and DeepDive will automatically create the table if it is saved as:

[```]
input/table_dump.tsv.sh
[```]

Next, we need to declare the schema of this `table_dump` table in our `app.ddlog` file; we add the following lines:
```

It would be amazing if font sizes were configurable.

**Comment by espenhogbakk** [comment]
+1

**Comment by alvaromb** [comment]
@travs I would love to send a PR to solve this, but I don't know if you prefer to being able to set the body font under the settings screen or just drop the size from 16 to 12.

**Comment by MikiDi** [comment]
Hi,
I have also been wondering how this could be done, and reading through the code I noticed that apart from using the [github-markdown stylesheet](https://github.com/travs/markdown-pdf/blob/master/lib/github-markdown.css), markdown-pdf also compiles [your custom atom stylesheet](https://github.com/travs/markdown-pdf/blob/master/lib/markdown-pdf.js#L121) (located at `~/.atom/styles.less`) and adds it to the style rules for conversion to pdf. This means that you can customize the conversion by adding rules in your `styles.less` that override the properties in [github-markdown.css](https://github.com/travs/markdown-pdf/blob/master/lib/github-markdown.css).  
For changing the body font-size for example, add the following lines to your `styles.less`-file:  
```
.markdown-body {
  font-size: 12px !important;
}
```
I 've only tested with this particular property yet, but most work for others too I guess ...


Could also come in handy for #37 #52 #112?

**Comment by ziy** [comment]
@MikiDi 's suggestion works for me except that the font size of the table is not updated, until the following lines are added as well

```css
.markdown-body table {
  font-size: 12px !important;
}
```

There could be other parts of the markdown file that also need customized font changes, so I am wondering what would be the most convenient way to update all of them.

**Comment by dalzzing2** [comment]
Well. Do you know how to change font shape ?

**Comment by Etheryte** [comment]
@ziy I ran into the same issue today and since it annoyed me a lot I fixed it on my local install, I will make a generic PR about it over the coming weekend.

**Comment by BlueHatbRit** [comment]
It's pretty easy to change in the styles.less. Here's what I use:

```less
.markdown-preview {
    font-size: 11px;
}
```

If you do that then all your PDFs will have a default size of 11px. You don't even need to use `!important`.

**Comment by opensorceror** [comment]
@BlueHatbRit's suggestion worked perfectly my Ubuntu machine :smile:

**Comment by rwaldner** [comment]
This works well - except for the text in tables :( - at least for me

**Comment by ffhaddad** [comment]
I tried copying the github-markdown.css file from the link in this thread into my project directory and adding to my settings.json the following:

```
"markdown.styles": [
    "/home/ffhaddad/Documents/github-markdown.css"
]
```
But, nothing from the style-sheet seems to be getting applied. Tried to exit and reopen VSCode also.

**Comment by BlueHatbRit** [comment]
@ffhaddad this is an atom module, not a vscode module. As far as I know, the two are not interchangeable.

**Comment by Etheryte** [comment]
My [pull request](https://github.com/travs/markdown-pdf/pull/129) from October, which makes all font-sizes relative to the body, is still open, you can merge the changes to your local installation if you need it badly.

**Comment by ffhaddad** [comment]
@BlueHatbRit sorry, looks like the same author made this module for VS Code also and the issues exists there as well. So I thought it might be appropriate to post here.

As an FYI, I don't convert to PDF directly anymore. Instead I set the output to HTML and then I print to PDF. Solves the issues for me until a permanent fix is applied.

**Comment by BlueHatbRit** [comment]
@ffhaddad the atom module feeds from the atom stylesheet, so you don't have to define it separately.

I actually do the same, I have an npm module for converting markdown files to pdfs with stylesheets but it doesn't fit into an editor. (I won't link to it here, that might be rude).

**Comment by travs** [comment]
@BlueHatbRit 
Not rude at all, the project looks good.
I guess you have had success so far with it; would you mind if I tried to incorporate it as a dependency in this atom package?

**Comment by BlueHatbRit** [comment]
@travs fill your boots! The more usage people can get out of mdpdf the better in my opinion. However if you went down that route, it would be harder to stick to exactly what you see in the preview window. If that's a worry then it might be worth thinking about a bit more, if it's not something you're worried about then go for it.

Feel free to tag me any PR's or issues that you want a hand in, I'd be happy to get involved (when I get an internet connection back home again).

**Comment by travs** [comment]
Changing font size is supported in the ways mentioned above (by editing the custom CSS).
The default converter is now changed to `mdpdf`, so the default font size should be more reasonable now as well.

Closing withe these changes.
