### ISSUE TITLE
options.phantomPath

### ISSUE THREAD

**Issue by ivivisoft** [travs/markdown-pdf#107]
when I convert my markdown got a error ,let me setting options.phantomPath,Can you teach me where I can setting it

**Comment by A-CiKe** [comment]
Me too！
OS:windows 10.

**Comment by whizzo** [comment]
Same here!!

Arch Linux x64
Atom 1.6.2
markdown-pdf 1.5.0

**Comment by A-CiKe** [comment]
I downloaded the PhantomJS, and run correctly.But the problem still exists.
I deleted the corresponding code in the assert.js, the error is still there.
Do not know where to set the "options.phantomPath"。

**Comment by zhanglianx111** [comment]
Me too！

**Comment by seamusgalla** [comment]
Me too! Is there a way to set it manually? I can't seem to find one. I also tried reinstalling the package which didn't work. 
On Windows 7

**Comment by paul-arthurthiery** [comment]
Same thing here... Still no update

**Comment by cyranodesale** [comment]
Same here!

> markdown-pdf: AssertionError: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'

Windows 7
Atom 1.12.3
markdown-pdf 1.5.0

**Comment by mosauter** [comment]
I think this isn't really a problem of _markdown-pdf_ but of _html-pdf_. As a workaround you can edit the source of _html-pdf_ which is accessible via:

config-folder of atom > packages > node-modules > html-pdf > lib > pdf.js

In this file you can add the line (before line 34/35)

```javascript
this.options.phantomPath = "/path/to/phantomjs"
```

This solved the problem for me.

**Comment by JeremiahZhang** [comment]
Just do it like  @mosauter said, it solved the problem.

install phantomjs, 
find the path of phantomjs
then add:

```
this.options.phantomPath = "/path/to/phantomjs"
```

Thanks @mosauter

**Comment by travs** [comment]
This should not be a problem any more, since we have moved from `html-pdf` to `mdpdf` as the default converter. Closing given this.

**Comment by jensse** [comment]
Problem persist on my work-computer that sits behind a proxy.   Ubuntu 16:04 LTS
The directroy:

`~/.atom/packages/markdown-themable-pdf/node_modules/.bin` 
contain a number of softlinks 
`phantomjs ->../phantomjs-prebuildt/bin/phantomjs`
the link points to a nonexisting directory.

tried: 
 `ln -s /usr/bin/phantomjs phantomjs`
Failed
