### ISSUE TITLE
Page Break

### ISSUE THREAD

**Issue by dalzzing2** [travs/markdown-pdf#108]
Hello. First of all, Thanks for your tool.

I have a issue.  I need some page break.
Is there this function ?

I hope your answer.
Thank you.

**Comment by Cinders-P** [comment]
There is a `page-break` code snippet you can use. Or just add `<div class="page-break"></div>` directly.

**Comment by dalzzing2** [comment]
It doesn't work. 

I've made a md file. And I want to convert to pdf.

Is there any idea ?

**Comment by dalzzing2** [comment]
I've found just now.
The way is '<div style="page-break-after: always;"></div>'.
Thank you.
