### ISSUE TITLE
Inline links or anchors are not properly exported

### ISSUE THREAD

**Issue by jmdacruz** [travs/markdown-pdf#113]
Hyperlinks pointing to anchors on the same document (as those generated by https://atom.io/packages/markdown-toc) are not being properly rendered as hyperlinks to anchors on the resulting PDF document. Currently, the links are just rendered as is, which causes PDF readers to try and open a link to `file.pdf#link`, instead of mapping the link to a PDF anchor.

The expected result would be something similar to what you get when you save the markdown on Atom as HTML (context menu on top of the rendered markdown, `Save As HTML...`), and then using a browser like Chrome open the HTML file and "print it" as PDF. On this version of the PDF, the hyperlinks to anchors on the PDF work as expected (clicking on them scrolls to the right place on the document)

**Comment by xabbu137** [comment]
I guess this is the same as #133 ?

**Comment by GavinAndre** [comment]
I also found the same problem

**Comment by travs** [comment]
This is a limitation of the rendering engine being used right now. When `mdpdf` switches to puppeteer this may be fixed.

This also only occurs on some operating systems.

**Comment by travs** [comment]
This should work now with puppeteer
