### ISSUE TITLE
markdown-pdf: AssertionError: html-pdf: Failed to load PhantomJS module.

### ISSUE THREAD

**Issue by mountzf** [travs/markdown-pdf#114]
Hi~I installed markdown-pdf under the Windows 10 OS, while when I tried to execute the commad "convert to PDF", an error below occurred:

> markdown-pdf: AssertionError: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'

While I cannot find any binary like PhantomJS under its intallation directory. Waht should I do? 
Thanks.

**Comment by bowang14** [comment]
[This post](https://github.com/cakebake/markdown-themeable-pdf/issues/17)may help.

**Comment by mountzf** [comment]
@bowang14 Thank you~ I fixed this problem following that post.

**Comment by JonnyCBB** [comment]
I guess it may be nice for this issue to be closed now that it's been sorted :)
