### ISSUE TITLE
markdown-pdf: ReferenceError: callback is not defined

### ISSUE THREAD

**Issue by nilsdoubleu** [travs/markdown-pdf#118]
I am Using Ubuntu 16.04 and Atom Version 1.9.9. The error happens every time i want to convert a markdown-file to a pdf. It happens across multiple systems with multiple files.

**Comment by piccolbo** [comment]
Same on os x yosemite

**Comment by yay** [comment]
Still an issue. Markdown PDF 1.5.0, Atom 1.10.2, macOS Sierra.

**Comment by pcameron-** [comment]
Having this issue with markdown-pdf 1.5.0, Atom 1.10.2, Windows 7

**Comment by bnn-y** [comment]
I also have the issue Markdown PDF 1.5.0, Atom 1.10.2, macOS Sierra.

**Comment by 0mp** [comment]
Confirmed on macOS Sierra 10.12, Atom 1.11.2, markdown-pdf 1.5.0.

**Comment by sww1235** [comment]
Pull request #138  might fix this issue.

**Comment by travs** [comment]
Merged that PR; will re-open and investigate further if this continues to be reported.
