### ISSUE TITLE
PDF text not applies.

### ISSUE THREAD

**Issue by dalzzing2** [travs/markdown-pdf#125]
I've seen the answer of changing font size.

But I couldn't find the answer of how to change font shape when converting pdf.

How can I change font shape ?

**Comment by Cr4zySheep** [comment]
I'm not sure about what you want to do, but did you try the same trick as for change font size ?

Example to center text :
`.markdown-body h1 {
  text-align: center;
}`

**Comment by dalzzing2** [comment]
Sorry. I haven't experienced Eng yet.

Well. I want to change font style. For example, from 'Agency FB' to 'Arial'

**Comment by Cr4zySheep** [comment]
And if you edit stylesheet from files tab with `.markdown-body p { font-family: Arial; } for instance, does it works?

**Comment by dalzzing2** [comment]
I've solved it. But the way is not like you.

I've modified all fonts to "나눔고딕코딩" associated with font-family of the 'github-markdown.css' file.

p.s. > "나눔고딕코딩" is Korean language.

Thank you for answering.
