### ISSUE TITLE
Customize output path

### ISSUE THREAD

**Issue by Icarus-Xu** [travs/markdown-pdf#127]

**Comment by Etheryte** [comment]
Currently no, see [markdown-pdf.js#L191](https://github.com/travs/markdown-pdf/blob/master/lib/markdown-pdf.js#L191), however, adding a configuration option to either save to the same location automatically or prompt for a location isn't too difficult with the current code structure.

**Comment by linickx** [comment]
👍 ... I store all my notes in a single folder (_>1k files_) and typically want the PDF version to share, being able to drop the PDF into a default of downloads/desktop (_or be prompted_) would make this part of my workflow much better.

**Comment by Icarus-Xu** [comment]
thank you
