### ISSUE TITLE
Support for .txt files?

### ISSUE THREAD

**Issue by linickx** [travs/markdown-pdf#128]
Is it possible to add `.txt` as a supported valid extension?

Note: Not supporting `.txt` appears to be a common problem: #60, #81 and #82

**Comment by travs** [comment]
Yes, you're right. This is a good idea.

**Comment by travs** [comment]
Will include in next patch release (very soon).

**Comment by linickx** [comment]
Awesome 👍

**Comment by travs** [comment]
Should be in the latest release :)
