### ISSUE TITLE
No path or wrong markdown type

### ISSUE THREAD

**Issue by IIYAMA12** [travs/markdown-pdf#131]
<img width="459" alt="schermafbeelding 2016-10-11 om 10 17 19" src="https://cloud.githubusercontent.com/assets/14896875/19263286/edb9310a-8f9b-11e6-9688-fd80e697891a.png">

Happens with every file I want to convert.

**Comment by ocoal** [comment]
Hi, I have the same problem based on an uppercased markdown file extension (README.**MD**).
Changing the file extension to lowercase (README.**md**) fixed my issue.

**Comment by travs** [comment]
Have updated to support all filetypes. Closing now.
