### ISSUE TITLE
Indoc Links breaking on convertion

### ISSUE THREAD

**Issue by Olian04** [travs/markdown-pdf#133]
Linking like this `[Table of Contents](#table-of-contents)` to another part of the same document breaks when converting, then link is redirected to the directory where the PDF is saved.

Linking with a `#` should link to a heading (with the same name as the link) withing the PDF.

**Comment by bouncydot** [comment]
I would be interested in this issue, too. Actually it is pretty important but can't fix it on my own. Does anybody have an idea?

**Comment by lorenzo-arena** [comment]
Did someone find a solution for this?

**Comment by honza-kasik** [comment]
This is related to `html-pdf` which is used in this script. Issue has been already opened:  marcbachmann/node-html-pdf#286

**Comment by travs** [comment]
@honza-kasik is correct.
This is an issue with the rendering engine and not directly in control of this package.
We will update to the latest versions of all dependent packages as they come out.
When `mdpdf` changes to puppeteer for rendering we may also fix this issue at the same time.

being tracked [here](https://github.com/travs/markdown-pdf/issues/113)
