### ISSUE TITLE
output filename generation breaks if filename contains the string 'md'

### ISSUE THREAD

**Issue by fkleedorfer** [travs/markdown-pdf#135]
my file 'problemdescription.md' is converted to 'problepdfescription.md' (as displayed in the success message), but no file is saved.

**Comment by Alexanderwmc** [comment]
Yes ,me too,my file's name is 'simd.md',so I rename the file to 'sima.md',and it worked,then I rename the output PDF file to 'simd.pdf'.I think it seems like there is a little bug,but  not affecting the normal usage.

**Comment by travs** [comment]
Same issue as #154, should be fixed now
