### ISSUE TITLE
Docs: Not precise on how to use 'convert' command

### ISSUE THREAD

**Issue by joallard** [travs/markdown-pdf#137]
It says 'use the convert command'. Where? How?

**Comment by joallard** [comment]
I got it. The readme should say:

```
Go to `Packages > Markdown PDF > Convert`
```

To be even better, the option could be called "Generate PDF", that way we could type 'PDF' when using the command palette.

**Comment by travs** [comment]
Closing as duplicate of #142 (even though this one came first)
