### ISSUE TITLE
Fonts rendered in markdown-preview are not rendered in the final pdf

### ISSUE THREAD

**Issue by BlueHatbRit** [travs/markdown-pdf#139]
I have a markdown file and I've included a font change which is being reflected successfully in the markdown-preview. However it doesn't seem to be in the final pdf.

I'm not sure what information would be useful, so here is the stylesheet I'm using.

```less
.markdown-preview.markdown-preview {
  // General settings
  @import url('https://fonts.googleapis.com/css?family=Open+Sans');
  font-family: 'Open Sans', sans-serif;
  font-size: 11px;
```

Let me know if you need anymore info or alternatively if you have any ideas as to why this might be happening that would be great.

**Comment by travs** [comment]
Just going through the old issues that I didn't close before

@BlueHatbRit Hey, let me know if this is still a problem and we can re-open.
Probably works since we are using `mdpdf` now :)

**Comment by BlueHatbRit** [comment]
Yeah this has been fixed with the new render engine 👍
