### ISSUE TITLE
"Phatom.js script did not exit"

### ISSUE THREAD

**Issue by harshbhatt** [travs/markdown-pdf#14]
Trying to generate a pdf, and keep getting this error: 
```
Error: html-pdf: PDF generation timeout. Phantom.js script did not exit.
If the error is a timeout, try running the command again. c:\Users\Harsh\.atom\packages\markdown-pdf\lib\markdown-pdf.js:120
Converted successfully. Output in c:\Users\Harsh\Desktop\Readme.pdf 
```

I have tried running the command several times, but still keep getting this error. 

I can't actually open the .pdf it generates. Please excuse me if its a trivial problem - I am new to using atom. I also installed html-pdf and phantomjs mpm packages because for some reason I thought they were needed/the console was saying I was missing phantom.js

Thanks in advance.

**Comment by travs** [comment]
I found this error occurred when I had the file tree selected instead of the actual editor window.

If this is happening to you, make sure you have your editor selected then try the command again.

Will implement a fix for this specific instance of the problem.

**Comment by LaSanta** [comment]
In the case that the markdown is large and phantomjs does not exit after that, adding global.gc() [GARBAGE COLLECTION] to the file  and running it as node --expose-gc <filename>.js takes care of it...

**Comment by travs** [comment]
@LaSanta Interesting... I am also interested to see whether updating phantomJS will do anything. I'm about to do that, so if anyone redownloads please update this issue with your findings

**Comment by travs** [comment]
Ok, since we use a newer version of `html-pdf`, this is probably fixed. Closing for now.

**Comment by 9tor** [comment]
Hi I'm using command "html-pdf source.html destination.pdf" on node. It throw error
/usr/local/lib/node_modules/html-pdf/bin/index.js:30
if (err) throw err
^

Error: html-pdf: PDF generation timeout. Phantom.js script did not exit.
at ChildProcess. (/usr/local/lib/node_modules/html-pdf/lib/pdf.js:121:17)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
I'm using ubuntu 14.04.1 64bit. Node version 6.2.2
