### ISSUE TITLE
Explain the `convert` command

### ISSUE THREAD

**Issue by bseib** [travs/markdown-pdf#142]
This is a comment on the instructions. As a new Atom user and new markdown-pdf user, I have no idea what the `convert` command is, or how to find it. It would be helpful to have more explicit instructions to convert my markdown file to PDF.

**Comment by GusSand** [comment]
New to atom, so not sure where the convert command is. I right click, look on the menus and nothing. Please let us know. 

cheers
G

**Comment by kuparez** [comment]
Hey!
I see that question is old, but anyway c: \
To convert your \*.md file you should do the following:
1. Go in atom to the folder with your \*.md file;
2. Open file you want to convert;
2. Press `cmd+shift+p` on mac or `ctrl+shift+p` on linux or windows;
3. In command prompt in the top center of atom type `convert`.

**Comment by joallard** [comment]
(#137)

> I got it. The readme should say:

> > Go to `Packages > Markdown PDF > Convert`

> To be even better, the option could be called "Generate PDF", that way we could type 'PDF' when using the command palette.
