### ISSUE TITLE
Can not add a default header or footer using the markdown.js file with header/footer objects

### ISSUE THREAD

**Issue by angelr91** [travs/markdown-pdf#147]
Hi,

I have been looking through hell and high water to find how to do a simple text footer and header to add to my markdown notes when i convert them to PDF. I feel i have tried everything with little luck. Only thing that has worked was physically put CSS into my markdown notes which using a text expander with autohotkey it works, but it is not an elegant solution. Do you all know how i can apply what is on this website. https://www.npmjs.com/package/html-pdf. To be able to apply the header and footer. I have literally placed the exact code from that site and no text appears on my header.

I have also edited the styles.css on atom. That only worked to add an image of my company logo to the bottom right (where i wanted it to) for my notes, but it doesn't add it to every PDF page as it should but of course this is becuase i'm editing the CSS. This is why i feel that the JS file for markdown-pdf is where i need to reside and apply any changes. 

any help?? I would greatly appreciate any anecdotal help.

Thanks

Miguel

**Comment by travs** [comment]
Uber-late reply: this is going to be implemented at some point in the future over [here](https://github.com/travs/markdown-pdf/issues/163), for now, use the `force fallback mode` option in this package's settings.
