### ISSUE TITLE
Accented characters render incorrectly

### ISSUE THREAD

**Issue by gerg0** [travs/markdown-pdf#148]
Accented characters (öüóőúéáűí etc.) render incorrectly in math formulas.

![image](https://cloud.githubusercontent.com/assets/18550215/23101218/a541a7f4-f68e-11e6-9358-6b72b14e874f.png)

I use Atom 1.114.3 x64 and markdown-preview-plus. My documents shows up correctly in the preview.

**Comment by travs** [comment]
`markdown-preview-plus` support has been deprecated for this package, and anything to do with math styles is being tracked in [this issue](https://github.com/travs/markdown-pdf/issues/186)
