### ISSUE TITLE
Render clickable links in PDF output

### ISSUE THREAD

**Issue by travs** [travs/markdown-pdf#15]
As @beltex said in #9, this is probably due to the way phantomjs renders the doc on osx. 
Raising a new issue in case it is not.

**Comment by morphy76** [comment]
Also in my environment 

> __Atom__ version 0.169.0
> __Environment__
> Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz - 8Gb RAM
> OpenSuSE 13.2 (kernel 3.16.7-7-desktop) x86_64
> Qt: 4.8.6 KDE: 4.14.3
> __Python__ version 2.7.8

links generated by markdown-toc are not clickable (even if they appear as clickable)

**Comment by travs** [comment]
Right, this is unfortunately out of our control as it's the way PhantomJS renders the document.

You can try using a package like [broadcast](https://atom.io/packages/broadcast) to get the markdown preview into Chrome, then print to a PDF.

**Comment by ryangyoung** [comment]
I would just like to add that this is fairly important functionality for production-ready PDFs. Users are accustomed to clickable links in PDF documents for navigation. If it's not possible to render the document with clickable links at this time, it would, in my opinion, be better to completely strip the links from the PDF output. That would at least preclude some potential user confusion.

**Comment by travs** [comment]
@ryangyoung Good point. I'm going to update the dependencies soon and this may be fixed for us anyway

**Comment by lfaoro** [comment]
Why is this issue closed if not solved yet? Same issue on Windows so it's not related to the way the doc gets rendered on OSX

**Comment by NKMR6194** [comment]
@lfaoro 

Because it is issue of `html-pdf`.
`markdown-pdf` depends on `html-pdf`.
Please see https://github.com/marcbachmann/node-html-pdf/issues/63

**Comment by beltex** [comment]
This seems to now be fixed as well (with #9) as of version `1.4.2`.

**Comment by travs** [comment]
Done!
