### ISSUE TITLE
Font of the resultant PDF is too large

### ISSUE THREAD

**Issue by pitosalas** [travs/markdown-pdf#151]
Is there any setting anywhere at all where I can control this? (I am using markdown_preview also, in Atom. Latest versions of everything. Thanks!

**Comment by RobertTalbert** [comment]
Same question and issue. Is there a way control the font size, and if so what's the best/easiest?

**Comment by FelixZY** [comment]
I too would like a better way to change the font size of the output pdf. However, as a temporary (and imperfect) workaround it is possible to add the following:
```css
<style>
body, p, li {
   font-size: .85rem;
}
</style>
```
This does not affect all text, such as headlines, but most of it.

**Comment by purplediane** [comment]
@FelixZY Where do I add this? 
I was so excited to find this package for Atom, but the result is not usable for me.

**Comment by FelixZY** [comment]
@purplediane nice find. So far I've been putting the tag right into my markdown document.

Obviously it is possible to edit the global styling (as you did @purplediane) as well as the local styling (style tag in the specific .md file)

**Comment by FelixZY** [comment]
There is another issue regarding this as well as a 12-month old pull request with a fix. Is this repository active?

#104
#112

**Comment by purplediane** [comment]
@FelixZY I hope this Repo is active. I am so happy to find this plugin. Also, thanks for the info about the style - I am rather new to markdown and didn't know that you could put style stuff right into the markdown file.

**Comment by tim-ballard** [comment]
No commits for over 12 months doesn't look promising

**Comment by roccomuso** [comment]
+1

**Comment by travs** [comment]
@tim-ballard @purplediane @FelixZY 
I'm back, guilty as charged for not merging quick fixes folks were kind enough to send.
Expect many upgrades in the coming days, this issue among them.

**Comment by travs** [comment]
Good discussion here, but I will close this one as a duplicate of #104
