### ISSUE TITLE
About latex-formula Convertion

### ISSUE THREAD

**Issue by Qingchuan-Ma** [travs/markdown-pdf#152]
it can't convert latex.  pity!

**Comment by Moghi** [comment]
I guess that's because LaTex is not markdown.

**Comment by travs** [comment]
Indeed, this package only supports conversion of markdown syntax documents.

Although for formulas there may be alternatives to convert latex formulas into something markdown can render (e.g. an image), so maybe [try something here](https://stackoverflow.com/questions/11256433/how-to-show-math-equations-in-general-githubs-markdownnot-githubs-blog).

Note I haven't given this a shot myself.
