### ISSUE TITLE
Add option to break page in output PDF

### ISSUE THREAD

**Issue by northcoders-chris** [travs/markdown-pdf#153]
Just a quick one. Any way of starting a new page? Currently using break tags.

**Comment by travs** [comment]
Sorry; just going to support the github flavour of markdown now, which does not have a pagebreak in its spec from what I know.
There may be promise in something like [this](https://stackoverflow.com/questions/22601053/pagebreak-in-markdown-while-creating-pdf) for others looking for this feature

**Comment by arkuuu** [comment]
Page breaks can be inserted with HTML:
```
<div style="page-break-after: always;"></div>
```
like mentioned [here](https://stackoverflow.com/a/29642392).
That worked for me with this plugin.
