### ISSUE TITLE
:word: displays broken image

### ISSUE THREAD

**Issue by dalzzing2** [travs/markdown-pdf#166]
OS Version : Windows 7
Markdown pdf : 2.0.4

I have a problem.
How to display a word between colon and colon?

I tried two ways.
One is' jdbc&#58;goldilocks&#58;// 192.168.0.5:22581/test'.
the other is 'jdbc:goldilocks://Server IP:Database listener Port/test'.

First thing display $#58; and it is unrefined.
Second display just broken image.

I want to display 'jdbc:goldilocks://...'

Do you know the way? or is it a bug?

        Driver Name : 원하는 드라이버 명을 입력한다.
     
        Description : 드라이버 명의 설명을 입력한다.
 
        Database    : Other 를 선택한다.
   
        JDBC URL    : Goldilocks URL 은 다음과 같다. ( 띄어쓰기 제외 )
 
                             jdbc:goldilocks://Server IP:Database listener Port/test
                                   => Display with broken image
                            위의 테스트 서버에서는 URL 이 다음과 같다.
           
                             jdbc&#58;goldilocks&#58;// 192.168.0.5 : 22581 / test
                                   => Display &#58;goldilocks&#58
`

**Comment by dalzzing2** [comment]
I forgot atom and apm version.
Here is my version.



C:\Users\PSH>atom --version
Atom    : 1.19.7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

C:\Users\PSH>apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python
git 2.13.3.windows.1
visual studio

**Comment by travs** [comment]
@dalzzing2 
Bug confirmed on Linux as well; thanks for the report. Will investigate and push a fix ASAP.

**Comment by travs** [comment]
It *seems* that this is caused by the emoji conversion in `mdpdf` ([here](https://github.com/BlueHatbRit/mdpdf/blob/32247f9730858aba701b8c2360a7848d1a5042c2/index.js#L68)).

cc: @blueHatbRit I notice that you have observed this before, by the timestamp comment in my link.
I suppose turning off emoji conversion is the solution for now? (Will add an option for this in the config).

**Comment by BlueHatbRit** [comment]
Yeah, sadly the showdown-emoji attempts to translate anything wrapped in colons with no spaces. It has been recently open sourced though so there may be a patch that could be submitted to that repo to correct the behaviour.

If you post an issue on mdpdf linking to this, I'll see if I can get to it next week (moving house this week). I'll then at least give it a crack and see if we can get a reasonable fix added!

**Comment by travs** [comment]
@BlueHatbRit Awesome! 
@dalzzing2 See the new config in `markdown-pdf@2.0.5`, and disable emoji conversion (`false`).
Should be good to go!

**Comment by dalzzing2** [comment]
@BlueHatbRit @travs Thank you guys.

**Comment by BlueHatbRit** [comment]
This has now been [fixed](https://github.com/BlueHatbRit/mdpdf/issues/30) with no updates required, @travs you'll just need to re-pull mdpdf and turn off the flag disabling emojis.

Credit to showdown-emoji folks for the fix 👍
