### ISSUE TITLE
not work four spaces under number

### ISSUE THREAD

**Issue by dalzzing2** [travs/markdown-pdf#170]
1. Title

    content

'content' is not blockquoted.

C:\Users\PSH>atom --version

Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

C:\Users\PSH>apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python
git 2.13.3.windows.1
visual studio

### Prerequisites

* [x] Reproduced the problem in Safe Mode (may not be approriate if your error involves markdown-preview-plus): http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [x] Checked that the issue isn't already filed: https://github.com/travs/markdown-pdf/issues)

### Steps to reproduce

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Input

If your markdown document does not contain sensitive information, it is easier to diagnose with the exact contents of the file.
You can create a gist of the file and paste the link here: https://gist.github.com

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

**Comment by travs** [comment]
This is supported by the rendering engine we switched to (mdpdf)
