### ISSUE TITLE
Syntax highlighter not working

### ISSUE THREAD

**Issue by lorenzo-arena** [travs/markdown-pdf#171]
I have a problem using this plugin with Atom. It always works perfectly but I can't get syntax highlighting, even if in markdown-preview I get my snippets nicely coloured.

- OS: Windows 10
- Atom: v1.18.4
- markdown-pdf: v2.1.0

Is there something I can do to fix this?

**Comment by yelantingfeng** [comment]
same problem on Win10.

**Comment by travs** [comment]
@lorenzo-arena @yelantingfeng 
Late reply:
Please update and try again, since we use mdpdf now, and it does support syntax highlighting.
Provide an example along with system/atom/package version specs if you can't get it to work, and we can re-open.
