### ISSUE TITLE
Numbered list syntax not properly supported

### ISSUE THREAD

**Issue by gmaletic** [travs/markdown-pdf#172]
### Prerequisites

* [x] Reproduced the problem in Safe Mode (may not be approriate if your error involves markdown-preview-plus): http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [x] Checked that the issue isn't already filed: https://github.com/travs/markdown-pdf/issues)

### Issue description

Only the first "bullet" should define the list bullet type. Markdown-PDF doesn't handle the case where the first bullet is a number and the following bullets are hyphens.

### Steps to reproduce

**Expected behavior:**

One way to format numeric lists is:

```
1. Item One
- Item Two
- Item Three
```

…and by Markdown definition, it should render as:

```
1. Item One
2. Item Two
3. Item Three
```

**Actual behavior:**

Renders as:

```
1. Item One
• Item Two
• Item Three
```

### Input

If your markdown document does not contain sensitive information, it is easier to diagnose with the exact contents of the file.
You can create a gist of the file and paste the link here: https://gist.github.com

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

**Comment by cutty853** [comment]
I will also add this unexpected behavior:
### Steps to reproduce

#### Expected behavior:

One way to format numeric lists is:
```
1. Item One
* subitem one
* subitem two
2. Item Two
* subitem one
* subitem two
```  
…and by Markdown definition, it should render as:
```
1. Item One
• subitem one
• subitem two
2. Item Two
• subitem one
• subitem two
```  
#### Actual behavior:

Renders as:
```
1. Item One
• subitem one
• subitem two
1. Item Two
• subitem one
• subitem two
```

**Comment by travs** [comment]
@bluehatbrit

Is this something you would want to support in mdpdf syntax? (sorry for all the notifications all of a sudden :smile: )

**Comment by BlueHatbRit** [comment]
This is interesting, it would be helpful to know which markdown spec is being used here. There are a few floating around, our markdown->html engine is actually showdown which has been used in a number of large markdown editors such as the old Ghost Blog editor etc so this might be upstream of mdpdf potentially if it is in the spec they use.

**Comment by travs** [comment]
@BlueHatbRit From what I can tell, they use [GFM](https://github.github.com/gfm/#what-is-github-flavored-markdown-) in the preview.
I checked the spec of GFM though, and actually the behaviour of mdpdf/showdown is correct, and there is a bug in `markdown-preview` rendering instead.

The spec is [here](https://github.github.com/gfm/#list-items). It looks like they're not fixing bugs over there right now though, unfortunately

**Comment by BlueHatbRit** [comment]
I've just tried this via Showdown's demo editor as well and it renders the actual behavior lists. Showdown implements the original markdown spec by John Gruber.

We then have [CommonMark](http://commonmark.org/) which seems to have support from GitHub, but GitHub then have GitHub Flavoured Markdown (GFM) which is a further extension of CommonMark.

There is scope to add multiple markdown flavours into mdpdf, this would be no problem but we'd need to find suitable modules which would handle this. While the dream is to later on build out mdpdf's own md->html converter for better control, it wouldn't be feasible for three modules without more contributors. If we're able to identify a good module for handling md->html for GFM then I'd be happy to give it a test and see if we can fit it in.
