### ISSUE TITLE
为什么 在mac上不支持png 或者jpg的导出?

### ISSUE THREAD

**Issue by jiaxiaogang** [travs/markdown-pdf#173]
# 为什么 在mac上不支持png 或者jpg的导出?

**Comment by centell** [comment]
I have same issue. not supported png or jpg on mac (high sierra)

**Comment by centell** [comment]
oh, If i write '![image](/img/1-1.png)', then it doesn't work but '![image](img/1-1.png)' then it works.

**Comment by jiaxiaogang** [comment]
ok;thanks for reply;

**Comment by centell** [comment]
I edit my comments

**Comment by jiaxiaogang** [comment]
what's your mean? my english is very bad!veryveryBad!

**Comment by jiaxiaogang** [comment]
I think your mean is:"let all image like this__ "img/xxx.png";then it can export jpg or png;" is it?

**Comment by jiaxiaogang** [comment]
shit I found you isn't author;hahahaha;

**Comment by centell** [comment]
@jiaxiaogang oh, I'm sorry I'm late. if you want export png image then using " ./img/xxx.png "

**Comment by travs** [comment]
Have deprecated support for other imagetypes than pdf
