### ISSUE TITLE
The following error occurred using markdown-pdf

### ISSUE THREAD

**Issue by lixiaodongdg** [travs/markdown-pdf#176]
<img width="485" alt="2017-11-02 1 25 18" src="https://user-images.githubusercontent.com/16541083/32312857-ee29ae32-bf6d-11e7-8195-7079b57e34b5.png">
Is it necessary to install nodejs?

**Comment by martinduvergey** [comment]
Same error here.

**Comment by travs** [comment]
Late reply, but need to open the console by clicking that button and paste more information here.
