### ISSUE TITLE
Time format error

### ISSUE THREAD

**Issue by timbby** [travs/markdown-pdf#179]
when I write an time as string in a json,the format ":30:" will become to a white box.

**Comment by diffyintegry** [comment]
I was also seeing this issue - It shows up for `:mm:` and `:mmm:` as well.  

It looks like it's related to the emoji handling.  When I disable emoji handling, the issue no longer shows up.  Possibly it's placing a checkbox when it can't find an emoji matching the characters inside the colons?

**Comment by travs** [comment]
Late reply, since I only have time to look at these now, but this was certainly due to the emoji handling. 
Was fixed [here](https://github.com/BlueHatbRit/mdpdf/issues/30), and newer versions of this package no longer have the problem.
