### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wangrx33** [travs/markdown-pdf#180]
### Prerequisites

* [ ] Reproduced the problem in Safe Mode (may not be approriate if your error involves markdown-preview-plus): http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [ ] Checked that the issue isn't already filed: https://github.com/travs/markdown-pdf/issues)

### Steps to reproduce

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Input

If your markdown document does not contain sensitive information, it is easier to diagnose with the exact contents of the file.
You can create a gist of the file and paste the link here: https://gist.github.com

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

**Comment by wangrx33** [comment]
why can't convert

**Comment by travs** [comment]
Sorry, I'm not sure what the problem is. I know this is really old by now, but please post the full error message in a new issue if you are still having a problem.
