### ISSUE TITLE
Headings Aren't Working in Lists

### ISSUE THREAD

**Issue by snehamabraham** [travs/markdown-pdf#185]
### Prerequisites

* [x] Reproduced the problem in Safe Mode (may not be appropriate if your error involves markdown-preview-plus): http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [x] Checked that the issue isn't already filed: https://github.com/travs/markdown-pdf/issues)

### Issue description
     When I try to use headings in a unordered list, in the preview they appear as the heading, but in the PDF they are normal lines in the list preceded by #'s 

### Steps to reproduce
Create an unordered list with headings. 
**Expected behavior:** [What you expect to happen]
The headings should match the appropriate font size, etc whether in a list or not. 
**Actual behavior:** [What actually happens]
The headings work when they are used normally, and do not work when used in a list. 
### Input

If your markdown document does not contain sensitive information, it is easier to diagnose with the exact contents of the file.
You can create a gist of the file and paste the link here: https://gist.github.com/snehamabraham/d17d0d42eccc67b5aa5106b2a66286f5

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.24.1
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.1
python
git
visual studio

On Windows 10 Home

![md-pdfissue](https://user-images.githubusercontent.com/24279327/37320223-08b7e862-2649-11e8-8e6f-2d399866c478.png)
[SampleMD.pdf](https://github.com/travs/markdown-pdf/files/1805309/SampleMD.pdf)

**Comment by travs** [comment]
This one is actually fixed by simply putting newlines around the list items with headings on them.
Like:
```
hello

- ### abc

  - #### def
```


[Related](https://github.com/showdownjs/showdown/issues/495#issuecomment-361013538)
