### ISSUE TITLE
img style ignored?

### ISSUE THREAD

**Issue by ronaldpetty** [travs/markdown-pdf#187]
### Prerequisites

* [x] Reproduced the problem in Safe Mode (may not be approriate if your error involves markdown-preview-plus): http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [x] Checked that the issue isn't already filed: https://github.com/travs/markdown-pdf/issues)

### Issue description

Image size is incorrect in pdf. 

### Steps to reproduce

Install latest beta atom, latest version of plugin, render markdown with image to pdf.

Image to be half the width.

Image is 100%

### Input

From atom style sheet.

img {
  width: 50%;
  border: none;
  background: none;
}

Example image in markdown

![something](images/something.png)

### Versions

1.26.0-beta1

uname -a
Darwin my-MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.1

**Comment by travs** [comment]
This is odd, since it works just fine on my system. Maybe there is a syntax error somewhere in your `styles.less`, or some other issue. I can't see the image unfortunately, but it might help to copy the html from the preview pane (right click -> copy html) and paste it in a gist and post it here.

**Comment by travs** [comment]
this was likely due to the issue described [here](https://github.com/travs/markdown-pdf/issues/165).
The fix is to put your styles in a selector `.markdown-body`, and they will be respected.
Can re-open if this does not work for you
