### ISSUE TITLE
converting doesn't work anymore

### ISSUE THREAD

**Issue by ghost** [travs/markdown-pdf#188]
### Prerequisites

* [x] Reproduced the problem in Safe Mode (may not be approriate if your error involves markdown-preview-plus): http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [x] Checked that the issue isn't already filed: https://github.com/travs/markdown-pdf/issues)

### Issue description
Everytime I want to convert a markdown file into a pdf, i get an error and nothing happens.

### Steps to reproduce

**Expected behavior:** That the plugin converts markdown to pdf

**Actual behavior:** spitting errors

### Versions
Atom 1.25.1
apm 1.19.0
Arch Linux
4.15.15-1-ARCH

**Comment by jbdrvl** [comment]
Same here, with error: `No available version compatible with the installed Atom version: 1.23.1`

**Comment by travs** [comment]
> spitting errors

looks like this user deleted their account, so I won't ever get an description of what these errors were.

@jbdrvl 
Try upgrading atom, that should help. I'm running `1.27.1` and it is working. Let me know if you still have problems afterward in another issue.
