### ISSUE TITLE
Request: Option to insert page break on horizontal rule

### ISSUE THREAD

**Issue by pippinbarr** [travs/markdown-pdf#191]
**Feature request**

Setting to enable page break in PDF on --- in markdown.

**Rationale**

This package is so wonderful for quickly producing good enough PDFs for distribution, but could really use a way to introduce page breaks. An option that would replace horizontal rules with page breaks seems like a pretty unobtrusive way to do that.

**Comment by travs** [comment]
This actually works for me on both the regular and legacy (fallback) modes of the package.

What syntax are you using exactly? Note that it may require a linebreak before and after the `---`, like this:

```
hey

---

there
```

**Comment by pippinbarr** [comment]
Huh, weird. I tested it out with varying amounts of whitespace/linebreaks around the --- but to no avail...

**Comment by pippinbarr** [comment]
Yeah that's my experience...

**Comment by MoritzBru** [comment]
It's also not working for me. Tested with and without legacy mode.
Would be a great feature ;)

```
Atom    : 1.28.2
Electron: 2.0.5
Chrome: 61.0.3163.100
Node    : 8.9.3

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.2
python 3.6.1
git

Win10
```

**Comment by Croydon** [comment]
Doesn't work for me either no matter if I'm trying it with legacy mode or without.

Atom 1.32.0 x654 Win10

**Comment by travs** [comment]
I misunderstood page break two years ago lol.

To do this we can add a CSS style, either inline or in your preferred styles file.
Then use a `div` with class `pagebreak`.

```
<style>
@media print {
    .pagebreak { page-break-before: always; } /* page-break-after works, as well */
}
</style>

<div class="pagebreak"> </div>
```

From here: https://stackoverflow.com/questions/1664049/can-i-force-a-page-break-in-html-printing/1664058
