### ISSUE TITLE
Syntax-error: block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by leomanso** [travs/markdown-pdf#195]
### Issue description
First of all, congratulations for your plugin, it is really awsome.
I'm open this issue more for give some information than to report a bug.
I was using atom 1.4 (a really old version) and tried to install your package. When i tried to convert the markdown text to pdf this error occurred: **Syntax-error: block-scoped declarations (let, const, function, class) not yet supported outside strict mode**. I search a lot trying to solve this problem when i finnaly decided to check my atom version. 
To solve the problem i just download the latest version of atom.
Maybe could be interest put into readme file the compability of the package with the versions of atom and other requirements.

### Steps to reproduce

1. Install markdown-pdf in a old version of atom.
2. Write some markdown text.
3. Try to convert markdown to pdf using the package installed.

### Versions
Node: 8.11.2
Npm: 5.6.0
Atom: 1.4.3
Markdown-pdf: 2.2.0

**Comment by travs** [comment]
This one should be resolved
