### ISSUE TITLE
Output Directory not working as expected

### ISSUE THREAD

**Issue by ajbraus** [travs/markdown-pdf#199]
### Prerequisites

* [x ] Reproduced the problem in Safe Mode (may not be approriate if your error involves markdown-preview-plus): http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [ x] Checked that the issue isn't already filed: https://github.com/travs/markdown-pdf/issues)

### Issue description

Need better explanation of how to set output directory.

I've created a `_pdfs` directory in the same directory as my `.md` files, and set the output directory to `/_pdfs`, and the pdf still is produced in the same directory as the `.md` file is in.

### Steps to reproduce

**Expected behavior:** Expected PDFs to be put into the `/_pdfs` directory

**Actual behavior:** PDFs are put in the same directory as the `.md` file.

### Input
none

### Versions

Atom    : 1.31.2
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by travs** [comment]
If you set it to `/_pdfs`, then the extension will try and save the file to `/_pdfs`, which is at the root of your filesystem, so that might have been the issue
