### ISSUE TITLE
Uncaught Error converting to image format

### ISSUE THREAD

**Issue by kyodev** [travs/markdown-pdf#203]
### Prerequisites

* Nota: parldown-pdf is **not visible** in Safe Mode

[Enter steps to reproduce:]

1. images with absolute **or** relative path
2. convert...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Debian GNU/Linux - Buster / debian10
**Thrown From**: [markdown-pdf](https://github.com/travs/markdown-pdf) package 2.2.0

### Stack Trace

Uncaught Error converting to image format. Check console for more information.

```
At /home/kyodev/.atom/packages/markdown-pdf/lib/fallback.js:92

undefined
```

### Commands

```
     -5:02.0 markdown-pdf:convert (input.hidden-input)
     -0:44.3.0 markdown-preview:toggle (input.hidden-input)
  2x -0:13.3.0 intentions:highlight (input.hidden-input)
     -0:11.7.0 core:save (input.hidden-input)
     -0:07.3.0 markdown-pdf:convert (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete 0.47.0 
busy-signal 2.0.0 
french-menu 0.2.2 
intentions 1.1.5 
linter 2.2.0 
linter-shellcheck 1.5.0 
linter-ui-default 1.7.1 
markdown-pdf 2.2.0 
structure-view 0.2.1 
symbols-tree-view 0.14.0 
teletype 0.13.3 
```

**Comment by fschlz** [comment]
I also keep having issues, when converting images to pdf.

Atom: 1.42
markdown-pdf = 2.2.0
macOS: 10.15.2

**Comment by travs** [comment]
Not enough context in error message; closing
