### ISSUE TITLE
Produces a 'Space' after every W, no matter the next character. 

### ISSUE THREAD

**Issue by Runawaygeek** [travs/markdown-pdf#204]
### Prerequisites

* [ ] Reproduced the problem in Safe Mode (may not be approriate if your error involves markdown-preview-plus): http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [ ] Checked that the issue isn't already filed: https://github.com/travs/markdown-pdf/issues)

### Issue description
After every use of "W", the PDF copy will have a space. 

### Steps to reproduce

This is my MD text, as <p>
"what were they watching"

When it outputs as a PDF it reads
"w hat w ere they w atching"

**Expected behavior:** [What you expect to happen]
No spaces

**Actual behavior:** [What actually happens]
Spaces

### Input
what were they watching

(Sorry, full file is confidential)

If your markdown document does not contain sensitive information, it is easier to diagnose with the exact contents of the file.
You can create a gist of the file and paste the link here: https://gist.github.com

### Versions

apm  2.1.3
atom 1.34.0

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

**Comment by jrg94** [comment]
I have the same issue: 

![image](https://user-images.githubusercontent.com/11050412/51563529-ae335380-1e5a-11e9-8c3a-7cd5dc791458.png)

**Comment by t-karcher** [comment]
Same here. Atom 1.38.2 with markdown-pdf 2.2.0

**Comment by JAFS6** [comment]
Same here. Atom 1.41.0 x64 with markdown-pdf 2.2.0

**Comment by travs** [comment]
This seems to have been a problem with phantomJS on some windows systems. It should no longer occur since we have changed to puppeteer in upstream `mdpdf` as the main converter.

Similar to #103
