### ISSUE TITLE
Bad kerning when generating PDFs on Windows 10.

### ISSUE THREAD

**Issue by SDx3** [travs/markdown-pdf#217]
### Prerequisites

* [x] Package is not available in safe mode.
* [x] Doesn't seem to be registered yet.

### Issue description

Bad kerning when generating PDF on Windows.

### Steps to reproduce

**Expected behavior:** Better kerning

**Actual behavior:** Terrible kerning.

### Input

See attached files.
- [keming.pdf](https://github.com/travs/markdown-pdf/files/3771907/keming.pdf)
- [keming.md.txt](https://github.com/travs/markdown-pdf/files/3771910/keming.md.txt)

Sorry about the choice of words, but I couldn't think of any word that starts with the letter F. Of course fuchsia comes to mind _after_ uploading.

### Versions

Atom 1.41.0x64 on Windows 10 (Microsoft Windows [Version 10.0.17763.805]).

**Comment by tmatijevich** [comment]
+1, Seems to be only for the gfm CSS

**Comment by travs** [comment]
This shouldn't occur any more since changing over to puppeteer instead of PhantomJS. We can re-open this if it still occurs for you.
