### ISSUE TITLE
Where the converted PDF will be stored?

### ISSUE THREAD

**Issue by habibalsaki** [travs/markdown-pdf#22]
Thank you for your plugin. But I can not find where the converted file has been saved. Can you please check this issue ?

**Comment by beltex** [comment]
Should be the same directory as the Markdown file you converted, with the same name, but with the `.pdf` extension.

**Comment by travs** [comment]
@habibalsaki 

@beltex is right; `mydir/myfile.md` -> `mydir/myfile.pdf`

**Comment by habibalsaki** [comment]
yes, thanks @beltex @travs 
that was a bit stupid question though ... but thanks
