### ISSUE TITLE
Unmaintained repository ?

### ISSUE THREAD

**Issue by jooola** [travs/markdown-pdf#224]
Hello @travs 
I wonder whether you still have an interest in maintaining this tools, or if you simply don't have enough time ?

Could we find something to get this project running ? Add another maintainer ? Redirect to a friendly fork of your project ?

They are many contribution, and I'd be happy to help.

Thanks for this work ! :tada:

**Comment by travs** [comment]
Hi @jooola ; yes, I think adding another maintainer would help, since I don't have much time to contribute code here myself. If you're interested in doing this, we could chat quickly about it. Do you have keybase, or another way to contact you besides github?

**Comment by jooola** [comment]
@travs You can find me on Freenode, Matrix, or email. I'd be happy to refresh this package. I didn't wait for your answer so I already rewrote your package https://github.com/jooola/markdown-to-pdf.
Tell me how we could get this to work again.

**Comment by travs** [comment]
@jooola Hi, can you email me? I don't see an email address in your profile. Thanks.

**Comment by jooola** [comment]
@travs Hey, sorry for not having contributed a bit to this project.

After I asked you for the push permission I used some other tool and I now moved away from Atom.

Cheers !
