### ISSUE TITLE
Rewrite the project

### ISSUE THREAD

**Issue by jooola** [travs/markdown-pdf#225]
@travs I propose you to import my project https://github.com/jooola/markdown-to-pdf into this one, and  do some kind or rewrite of the project in order to clean it up, and test it properly.

For now my project hasn't reached the same feature level as yours but I'd be happy to re implement them one at the time.

Tell me what you think.

**Comment by travs** [comment]
@jooola Thanks, I appreciate this a lot.

I've merged over most of the logic code from your fork now, except for the tests, since I haven't had a chance to look at them.
Would you mind bringing over the tests and making a PR? I will take a look at it ASAP.

**Comment by travs** [comment]
This issue is basically #76 now
