### ISSUE TITLE
Custom user styles doesn't work

### ISSUE THREAD

**Issue by sebvdk** [travs/markdown-pdf#228]
**Atom version** 1.45.0
**OS/Distribution** Linux/Archlinux
**Python version** 3.8.2

Hello,

I have an issue to apply custom CSS styles.

I create a custom CSS style in my "styles.less" from your example Tips : 

`.markdown-body {
  h1 {
    font-size: 5em;
  }
}`

No change detected on heading.
It's an issue or I will have missed something ?

Thank you in advance.

**Comment by travs** [comment]
@sebvdk Hi, this works on my machine (also arch).
Could you open the developer console (`ctrl-shift-i`) and do `atom.styles.getUserStyleSheetPath()`?
Make sure that this matches the styles file you're editing.

**Comment by sebvdk** [comment]
@travs Hi, here's result command :
`atom.styles.getUserStyleSheetPath()
"/home/seb/.atom/styles.less"`

I had a color property to header in less file and generate PDF : 
`.markdown-body {
  h1 {
    font-size: 10em;
    color: blue;
  }
}
`
Nothing happens, no change ... Very strange.
And I have no error or warning output in developer console.

I change selector "atom-text-editor" properties with success.

**Comment by sebvdk** [comment]
@travs You can ignore my issue.

I thought I installed your package. But I've installed @jooola maintainer package (markdown-to-pdf).
I installed you package and everything is working fine !
Sorry for my mistake.
Thank you !
