### ISSUE TITLE
It simply doesn't work

### ISSUE THREAD

**Issue by morphy76** [travs/markdown-pdf#24]
__Atom version__ 0.169.0
__Environment__
Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz - 8Gb RAM
OpenSuSE 13.2 (kernel 3.16.7-7-desktop) x86_64
Qt: 4.8.6 KDE: 4.14.3
__Python version__ 2.7.8

Atom plugin tree-view and preview available, clicking the _convert_ command from the _Packages->Markdown to PDF_ having an active MD file opened and focused doesn't trigger anything, it is just like doing nothing.

Listing the FS where the MD file is located, not PDF file is present

The plugin has been installed using the _install_ command from the Atom settings menu

**Comment by travs** [comment]
This is very strange behaviour.

So nothing shows up in the developer console at all?

:worried:

**Comment by morphy76** [comment]
Hi travs

how can I check the dev console?

**Comment by travs** [comment]
`view -> developer -> toggle developer tools`

**Comment by morphy76** [comment]
Thank you, got it
> Please save the file as a markdown (.markdown, .md, .mkd, .mkdown or .ron)

my file has .MD extension (uppercase)

**Comment by travs** [comment]
You raise a good point though; I will make it more obvious that there is an error in a future update.

Thanks for the report!
