### ISSUE TITLE
Comments after export to PDF

### ISSUE THREAD

**Issue by Naturjoghurt** [travs/markdown-pdf#27]
Comments like this:
```html
<!-- Test -->
```
get exported to PDF, meaning they are visible.

**Comment by travs** [comment]
Looks like there is an [issue in marked](https://github.com/chjj/marked/issues/253) for this.

There are actually two rendering options for `markdown-pdf`, but neither of them is perfect yet.

If you go to the settings page for this package you can change the renderer from `marked` to `markdown-preview` and this problem disappears.

I will soon be changing the default renderer to `markdown-preview` and may remove `marked` support altogether in the future.

**Comment by travs** [comment]
This looks to be fixed with recent updates.
Reopen if it persists.
