### ISSUE TITLE
Deprecated calls / selector

### ISSUE THREAD

**Issue by ho1ger** [travs/markdown-pdf#29]
The deprecation cop reports that atom.workspaceView is outdated but used in the add in. Furthermore the cop reports deprecated selectors.

Add in is still functional despite the warnings/errors

**Comment by travs** [comment]
@ho1ger 
Thanks for this, however I cannot pick up the deprecated call using the cop, even though it certainly is in my package.

Would you mind dumping the output of the cop for `markdown-pdf` besides the `workspaceView` call which you already mentioned?

**Comment by ho1ger** [comment]
After the update (I'm using 1.3.0 now) there is only one deprecated selector:

markdown-pdf
keymaps/markdown-pdf.json
Use the `atom-text-editor` tag instead of the `editor` class.

BR
