### ISSUE TITLE
Dark Syntax Highlighter

### ISSUE THREAD

**Issue by Code-Vortex** [travs/markdown-pdf#30]
First of all thanks for this great plugin, it works great for me , but i have one problem with it.
the screenshot you have containing dark background at the syntax area but for me its a white background which makes some colors hard to be seen however the markdown-preview showing me a dark background.
How can i turn it into dark background to be the same as the screenshot you have in the README file, is there a specific file should be modified ?

also there is a deprecated selector 

```
keymaps/markdown-pdf.json
Use the `atom-text-editor` tag instead of the `editor` class.
```

Thanks

**Comment by travs** [comment]
What OS are you on? What version of atom are you running? What version of this package?

Run these commands and tell me what you get for each:

```js
atom.themes.getActiveThemes()[0].stylesheets[0][0];

atom.packages.activePackages["markdown-preview"].stylesheets[0][0]

var user_styles = atom.styles.getStyleElements();
user_styles = user_styles[user_styles.length - 1];  //just give me the first line for this one
```

Deprecated selector was taken care of in #29; patch soon.

**Comment by Code-Vortex** [comment]
OS: Fedora 21
Atom Version: 0.175
Markdown-pdf Version: 1.3.0

```javascript
atom.themes.getActiveThemes()[0].stylesheets[0][0];
"/home/sasa/.atom/packages/monokai/index.less"
atom.packages.activePackages["markdown-preview"].stylesheets[0][0];
"/usr/local/share/atom/resources/app/node_modules/markdown-preview/styles/markdown-preview.less"
var user_styles = atom.styles.getStyleElements();
undefined
user_styles = user_styles[user_styles.length - 1];
<style source-path=​"/​home/​sasa/​.atom/​styles.less" priority=​"2">​/* * Your Stylesheet * * This stylesheet is loaded when Atom starts up and is reloaded automatically * when it is changed. * * If you are unfamiliar with LESS, you can read more about it here: * http://www.lesscss.org */</style>​
```

**Comment by Code-Vortex** [comment]
Is there something I should do to fix my problem ?

**Comment by travs** [comment]
Working on a solution.. I'll let you know what I come up with

**Comment by travs** [comment]
I have a feeling that it may be the updated version of markdown-preview that is causing this. If you are able to downgrade markdown-preview and give that a try it may work. That may be tricky though since it is a built in package.

**Comment by Code-Vortex** [comment]
unfortunately i wont be able to downgrade, can i add this one manually to `/home/$username/.atom/style.less` 

```css
.markdown-preview atom-text-editor {
background: #f8f8f8;
border: 1px solid #ccc;
font-size: 13px;
line-height: 19px;
overflow: auto;
padding: 6px 10px;
border-radius: 3px;
background: #282828;
border: 1px solid #0e0e0e;
}
``` 

I got it by using inspect element.

**Comment by travs** [comment]
You're right! :smile:

The solution is to add the ui styles, which I probably should have done long ago.

Will be releasing a patch later today with the final solution.

Thanks for your help :bug:

**Comment by Code-Vortex** [comment]
Glad that I can help! , but when adding the style above it didn't work, Do you mean that you got the idea of how to solve this issue , but the solution itself wont be the above style as it is ?

**Comment by travs** [comment]
Yeah, I meant the idea :wink: 

That's just as helpful though!

**Comment by Code-Vortex** [comment]
Sorry for interruption, Really i appreciate your efforts and time and i wish i could be more helpful, i just wanted to know is there a specific date for releasing a fix for this issue ? i just finish some articles and i would like to convert them into PDF asap using your package. in my time zone now its Monday 00:01 AM, thanks again !

**Comment by travs** [comment]
@Code-Vortex 
Convert away!

**Comment by Code-Vortex** [comment]
thanks @travs it works :+1:

**Comment by plttn** [comment]
I'm still getting the mismatch between preview and export. I can give you my repro file/theme, but I'm guessing that isn't much of a help.

![expected](https://lh3.googleusercontent.com/-EUvAO3r2PlU/VWantEmU6NI/AAAAAAAAUKg/kSQpeVCYsmY/s0/2015-05-27_22-29-28.png)

![actual](https://lh3.googleusercontent.com/-WUJ3XZF_U68/VWanzzKLQlI/AAAAAAAAUKo/AUYLWc47rNA/s0/2015-05-27_22-29-53.png)
```
atom.themes.getActiveThemes()[0].stylesheets[0][0];
"~\.atom\packages\tubster-syntax\index.less"
atom.packages.activePackages["markdown-preview"].stylesheets[0][0]
"%localappdata%\atom\app-0.202.0\resources\app.asar\node_modules\markdown-preview\styles\markdown-preview.less"
var user_styles = atom.styles.getStyleElements();
undefined
user_styles = user_styles[user_styles.length - 1];  //just give me the first line for this one
<style source-path="~\.atom\styles.less" priority="2">
```
