### ISSUE TITLE
User styles not working

### ISSUE THREAD

**Issue by travs** [travs/markdown-pdf#31]
#10 was supposed to be resolved by #11, but I have found that the following code does not give me my user style:
```js
var user_styles = atom.styles.getStyleElements();
user_styles = user_styles[user_styles.length - 1]
```

Replacing the second line with `user_styles = user_styles[user_styles.length - 2]` *does* give it to me though.

This brings up an issue @schmurfy [mentioned](https://github.com/travs/markdown-pdf/pull/11#issue-50013240), there should be a cleaner way to get styles.

**Comment by schmurfy** [comment]
Yeah that's not so great and even with that the there are still some styles which are not picked up but for me it works or at least it was working last time I checked.

I don't see the difference between the quote and what you replaced it with, what changed ?xD

**Comment by travs** [comment]
Woops, my user style was the *second* last so it was supposed to be `-2`. Edited now. My bad.
