### ISSUE TITLE
Issue with Base16-syntax theme installed

### ISSUE THREAD

**Issue by brianchung808** [travs/markdown-pdf#33]
At line 150:
https://github.com/travs/markdown-pdf/blob/master/lib/markdown-pdf.js#L150

When you have the base16 syntax theme (https://atom.io/themes/base16-syntax) installed, the `stylesheets` array is empty and the package fails silently. I get this stack trace:

```
"TypeError: Cannot read property '1' of undefined
  at getStyles (/Users/bchung/.atom/packages/markdown-pdf/lib/markdown-pdf.js:150:66)
 ...
```

I can only reproduce it with this theme (although I only tested monokai-theme which works fine).

Just a heads up to anyone using base16-syntax theme.

**Comment by travs** [comment]
Good catch. There may be other themes that result in this same behaviour, so I will implement something to safeguard against it.
Tks :bug:
