### ISSUE TITLE
Reduce output fiesize

### ISSUE THREAD

**Issue by MuscleRumble** [travs/markdown-pdf#35]
Woah! Didn't realize that the output .pdf is so huge!

5,6 MB for 10 pages (text only).
9,4 MB for 14 pages (text only).

What's up with that? It would be really cool if this issue is fixed, because I really like the idea of `markdown -> pdf`. :)

**Comment by travs** [comment]
What system are you on? 

I also experience this on OSX Yosemite, which is [mentioned in this comment](https://github.com/marcbachmann/node-html-pdf/issues/3#issuecomment-50259032).

This problem, along with #9 and #15 should be resolved when `html-pdf` makes the move to PhantomJS 2.0, which was just released.

**Comment by MuscleRumble** [comment]
Yep, OS X Yosemite 10.10.2! Alright, looking forward to an update! :)

**Comment by travs** [comment]
Touching this one again now. May be time to update the version of `node-html-pdf` we use here.

**Comment by travs** [comment]
Ok, since we use a newer version of `html-pdf`, this is probably fixed. Closing for now.
