### ISSUE TITLE
Uncaught Error: ENOENT, open 'c:\devel\tools\cpdfer\Readme.md'

### ISSUE THREAD

**Issue by benogle** [travs/markdown-pdf#36]
_From @baskinomics on February 4, 2015 5:43_

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'c:\devel\tools\cpdfer\Readme.md'

```
At fs.js:75

Error: ENOENT, open 'c:\devel\tools\cpdfer\Readme.md'
  at Error (native)

```

### Commands

```
     -0:24.5 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:17.5 core:confirm (atom-text-editor.editor.mini)
     -0:17.4 markdown-pdf:convert (atom-text-editor.editor.is-focused)
     -0:12.4 core:move-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 14,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
markdown-pdf, v1.3.2

# Dev
No dev packages
```

_Copied from original issue: atom/atom#5391_

**Comment by benogle** [comment]
_From @50Wliu on February 4, 2015 15:2_

/cc @benogle

**Comment by benogle** [comment]
I assume this is a issue with `markdown-pdf`.

**Comment by benogle** [comment]
Maybe some dir on the `c:\devel\tools\cpdfer\` path doesnt exist?

**Comment by travs** [comment]
@baskinomics

Do you still get this issue?

I am not quite sure what's going on here

**Comment by travs** [comment]
@hdmi @baskinomics

Hey there, I'm still trying to reproduce this issue and cannot. Is the .md file saved before you attempt to convert it?
Also, it is informative that this occurs on different operating systems. Is there any more information you thin may be pertinent to resolving this?

Thanks for the reports! :bug:

**Comment by hdmi** [comment]
I've done some tests and here are the outputs:

Open atom from terminal with normal rights (no sudo):
* Create a new document, write some markdown and save it as Document1.md
 * Output: ENOENT...
* Create a new document, write some markdown and save it as Document2.markdown
 * Output: It generates the file correctly

I have renamed my files ending with .md to .markdown and all the problems with the pdf conversion disappeared.

**Comment by baskinomics** [comment]
Sorry I haven't been contributing to this, haven't really been using Atom in the day-to-day workplace (yet ;). I can't remember exactly what I was attempting to do, but I can confirm that the path `c:\devel\tools\cpdfer\` does not exist on my machine.

**Comment by atdrago** [comment]
Hi everyone,

I've gotten this issue and I think I know the problem. The directory is probably supposed to be `c:\devel\tools\cmder\`, but it's replacing "md" at the wrong spot, leading to "cpdfer".

I have the same problem. My username is "adamdrago" and I get this error:

```
Uncaught Error: ENOENT: no such file or directory, open '/Users/adapdfrago/Desktop/Notes/geo-pd/GEO-PD.md'
```

Notice how "ada**md**rago" betcomes "ada**pdf**rago"?

Hopefully this helps solve the problem!!

**Comment by hdmi** [comment]
Thanks @atdrago for your help, now I realize where the problem comes from.
As you said, the package was replacing in the path a substring composed by 'md' to 'pdf'.

I have modified the function which returns the path of the new pdf file, and it seems to work perfectly.
You can see the modifications in the commit d0c1faf
