### ISSUE TITLE
Markdown links don't work in PDF 

### ISSUE THREAD

**Issue by ryangyoung** [travs/markdown-pdf#38]
I have a lot of links in my document that work fine as MD and HTML, but they are dead (i.e., unclicklable) in the outputted PDF. It would be great if the links worked in the PDF as they do in HTML. Or, failing that, strip them when they're converted to PDF--though that's less desirable. 

Thanks, 
Ryan

**Comment by beltex** [comment]
See https://github.com/travs/markdown-pdf/issues/15

**Comment by ryangyoung** [comment]
Got it. Thanks!

**Comment by beltex** [comment]
np! :)
