### ISSUE TITLE
Settings page not working correctly

### ISSUE THREAD

**Issue by Code-Vortex** [travs/markdown-pdf#42]
I have a wired problem, settings page not working correctly and i tired to remove the package and install it again but nothing happens. i don't know what to do.

the converter is working but the settings page is not. if i would like to convert to png , i have to type it inside not select-able like it was.

![screenshot from 2015-02-15 12 54 53](https://cloud.githubusercontent.com/assets/4104127/6203018/c1c99d42-b512-11e4-8074-df37c1155919.png)

**Comment by Code-Vortex** [comment]
Now another option disappeared by itself ! re-installing not helping me to, even removing atom and deleting .atom folder which  inisde my home directory however the other settings pages working with no error so i guess the problem with markdown-pdf itself.

![screenshot from 2015-02-15 15 56 28](https://cloud.githubusercontent.com/assets/4104127/6203443/7d96c9d8-b52b-11e4-815f-05aee5296a62.png)

**Comment by travs** [comment]
This has also happened to me recently, but it has happened with other packages as well.

I will raise the issue to atom/settings-view.

**Comment by travs** [comment]
@Code-Vortex It seems this issue was resolved with [these](https://github.com/atom/settings-view/issues/383) [changes](https://github.com/atom/settings-view/issues/356)
