### ISSUE TITLE
Improving markdown-pdf options.

### ISSUE THREAD

**Issue by Code-Vortex** [travs/markdown-pdf#44]
Due to the current settings-view package issue , i guess the only workaround is to use command platte (as they told me on that open issue) which only provides the commands provided by some package like markdown-pdf , and because i really like this package i had to think about another way to avoid settings issues in the future, then i need to ask you first , what are possibilities of adding something like this to markdown-pdf ? and how it will communicate with the rest of the code ?
I tried to figure out how the markdown-pdf.js know what you selected (pdf, png or jpeg) but i couldn't.

Here is what i want to be achieved, either by you or if could help me to achieve it:

![screenshot from 2015-02-23 11 53 56](https://cloud.githubusercontent.com/assets/4104127/6325781/bcc7965e-bb53-11e4-9345-6f4f66dcda6f.png)

**Comment by travs** [comment]
Hi @Code-Vortex, are you still getting these issues?

I just run a `convert` command from the menu before opening package settings and I don't get an error, so we wouldn't need this implemented if that was common between users.

**Comment by Code-Vortex** [comment]
For me I have custom modifications , that why I still wait until settings-view issue to be solved to be able to change the output type then I will test my custom modifications if they are working, and I was looking for alternative solution

**Comment by travs** [comment]
Apparently the settings view issue was solved ([refer to this issue](https://github.com/travs/markdown-pdf/issues/42)), so I'll close this now.
