### ISSUE TITLE
Not responding to font size changes

### ISSUE THREAD

**Issue by xyzxzyz** [travs/markdown-pdf#45]
First of all, I'd like to thank you for the great package. It's wonderful to go from markdown editing to a pdf output in a single command.

One small issue, though, is that font size in the generated pdf file is very tiny. I tried changing font sizes in the settings tab of both the editor and the package, but there is no change. It _is_ responding to theme changes, so I'm not sure what the problem is. (I'm new to atom, so I might be missing something completely obvious.)

**Comment by travs** [comment]
Thanks for the report @xyzxzyz 
Can you tell me what OS, you're on, what version of Atom you have installed, and maybe give an image of the small-font output?

There is no font parameter in the package settings, so perhaps you mean another package?

**Comment by xyzxzyz** [comment]
I'm using Windows 8.1 and Atom version 0.187.0. Here's a sample output image:

![image-0001](https://cloud.githubusercontent.com/assets/10797200/6883204/e75adb58-d55f-11e4-8749-66b977131f2c.jpg)

By package I meant changing package-specific settings by adding lines like  `"markdown-pdf": fontsize: 64` to `config.cson`, but I was probably doing it wrong.

**Comment by travs** [comment]
Apologies for taking so long to get back to this; I've been busy with other things.

@xyzxzyz
The option you tried to pass in is not implemented in the package, so there would be no effect for that reason. The tiny text output is mysterious though. Have you tried with an updated version of Atom? I'd like to get this sorted out now that I'm back.

**Comment by kflu** [comment]
Same issue here. Windows 10 user. Any updates?

**Comment by travs** [comment]
On year on, I'm not sure if this is still an issue. Closing for now; we can always reopen if it pops up again.
