### ISSUE TITLE
`Convert` is not responding

### ISSUE THREAD

**Issue by gujans** [travs/markdown-pdf#46]
I am having trouble generating any outpuf from markdown-pdf. Nothing seems to happen if the `convert` command is called. Not when called form the menu, neither from the keyboard shortcut. 

I am using version 1.3.5 of markdown-pdf.

**Comment by travs** [comment]
What operating system version are you using?

Also check the developer console (should be able to find it in View or
Developer menu) and see wqhat it outputs when you do the convert command

**Comment by gujans** [comment]
I just installed the package on my laptop which is basically the same setup as my workstation which I encoutered the problem on. Both run a 14.04 Ubuntu. On my laptop everything works very neatly.

I will be not on my workstation in the following week, but I will check the log as soon as I can get it. 

Thank you for this very useful tool!

**Comment by travs** [comment]
@gujans Did you ever get a chance to test this out?

**Comment by travs** [comment]
Closing due to no feedback.

**Comment by gujans** [comment]
I just got the chance to test the setup again. Everything works now. Thanks!

**Comment by travs** [comment]
@gujans Awesome!
