### ISSUE TITLE
The 'Convert' button doesn't work

### ISSUE THREAD

**Issue by Chibaheit** [travs/markdown-pdf#47]
Because of the GFW, the apm can't install the packages. I download it from your GitHub and move it to the ~/.atom/packages. It doesn't work when I click the covert button. 
OS : Yosemite 10.10.3
Atom: 187

**Comment by YuriSora** [comment]
![screen shot 2015-04-03 at 08 39 13](https://cloud.githubusercontent.com/assets/6986642/6976471/f9be62b6-d9dc-11e4-8b64-f451da2db808.png)

**Comment by travs** [comment]
Sorry what's the "GFW"?

And I believe it's not working when you install it outside `apm` because the dependencies (`hteml-pdf` being one of them) are not installed.

If there is an issue with installing from `apm` then resolving that should fix this issue.

**Comment by YuriSora** [comment]
GFW means Great Fire Wall. Chinese characteristic to keep us out of some websites such as youtube and github. Maybe the pan can't go through the VPN. THX

**Comment by travs** [comment]
@Chibaheit 
Did you ever find a solution to getting apm things installed through the GFW?

**Comment by travs** [comment]
Closing due to no feedback.
