### ISSUE TITLE
Supporting non-standard Markdown Previewer CSS

### ISSUE THREAD

**Issue by veltall** [travs/markdown-pdf#48]
## Issue
I use [`markdown-preview-plus`](https://github.com/Galadirith/markdown-preview-plus) for its excellent MathJax support (using the `mathjax-wrapper` to expose Atom's LaTeX library). This previewer cannot be used in conjunction with the Atom-provided `markdown-preview` package, so one has to be disabled for the other to be usable.

## Request
Failing an official resolution, I would appreciate any guidance in solving this issue just for my personal use. I can imagine two breakpoints:
1. The prepending CSS cannot be pulled from `markdown-preview`
2. `marked` does not support Mathjax

Thanks for the awesome work and any help.

**Comment by travs** [comment]
What error(s) are you getting? Those breakpoints seem reasonable, and 1 would be easy to fix while 2 would be a little more difficult.

**Comment by travs** [comment]
@veltall Anything ever happen to this on your end?

**Comment by travs** [comment]
Going to call this fixed due to merge of #88
