### ISSUE TITLE
Is it possible to change the output pdf font?

### ISSUE THREAD

**Issue by stavpup** [travs/markdown-pdf#52]
Output pdf has dejavusans font

**Comment by travs** [comment]
This could be a feature that someone could implement; I won't have time.

 Right now it's just using whatever the current style is.

**Comment by travs** [comment]
Noting here as well that this raises the larger issue of where to get styles from.

Should there be more options to enable further customization, or should the markdown-preview pane be mirrored as closely as possible?

**Comment by 21xhipster** [comment]
For me standalone stylesheet is better option :100:

**Comment by travs** [comment]
Going to close this one, as the best way to change font would be to simply change your atom user styles (`~/.atom/styles.less`)
