### ISSUE TITLE
Respect Github Style Option

### ISSUE THREAD

**Issue by exploide** [travs/markdown-pdf#56]
By now, markdown-preview supports GitHub style markdown rendering. While markdown-pdf respects the current Atom theme, it does not so with the new markdown-preview option concerning GitHub style.

**Comment by travs** [comment]
Can you show an example of the output you get vs expected output? Maybe a screenshot?

**Comment by exploide** [comment]
No problem.

The first image shows Atom with the Dark One theme. In the preference pane, you can see that GitHub style option is enabled and markdown-preview renders the Markdown theme independently using GitHub style. The second picture shows the output of markdown-pdf and as you can see it is still the theme dependent rendering ignoring the mentioned option.
![markdown-test](https://cloud.githubusercontent.com/assets/5670236/7778870/ce32ffc0-00cf-11e5-8b21-ac5bf3a9b2d2.png)
![markdown-pdf](https://cloud.githubusercontent.com/assets/5670236/7778874/d990f8e0-00cf-11e5-8ed0-814ed55540e8.png)

Beside that, Atom throws an error but I think this is already mentioned in #54 .

**Comment by travs** [comment]
Ok, I see what's going on here now.
This can certainly be added, and actually raises an important issue of how we get the styles in general. Right now, the style is just grabbed from the currently-active style in Atom, as you've demonstrated. 

I will add this to the feature request list I am compiling, and reopen if necessary.

Thanks for the report! :smile:

**Comment by travs** [comment]
Fixed by #72
