### ISSUE TITLE
Registering "undefined" callback

### ISSUE THREAD

**Issue by felipetavares** [travs/markdown-pdf#57]
Line 50 in markdown-pdf.js should be

    atom.commands.add('atom-workspace', 'markdown-pdf:convert', this.convert);

but it is:

    atom.commands.add('atom-workspace', 'markdown-pdf:convert', this.convert());

This causes an error that is reported at in [command-palette#42](https://github.com/atom/command-palette/issues/42)

(sorry for the formatting, I'm new to this)

**Comment by travs** [comment]
See #54
