### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by Stoo0rmq** [travs/markdown-pdf#60]
-DeepIn .Ubuntu 14.04.
-just Atom + markdown-pdf

When I tried to convert from a file to PDF , it didn't worked. I have tried using the shortcut ( ctrl+shift+c) and using the Packages menu. I also tried using a .txt and an empty extension file .

**Comment by travs** [comment]
OK, can you show me some output?

Try running it with Developer Tools open (View > Developer > Toggle Developer Tools) and see if there is any error output.

**Comment by hiroqli** [comment]
I meet same.
I receive message on console. 
> Please save the file as a markdown (.markdown, .md, .mkd, .mkdown or .ron)

I use .mdown for markdown file.

**Comment by jrauschenbusch** [comment]
Had the same problem while saving the file without any extension. Not a big deal to add the extension, but there is no single error message or a hint on the ui.

**Comment by travs** [comment]
@jrauschenbusch Ok good point. So this is actually two separate issues:
1. Add pointer in UI error message to look at developer console (and instructions on how to get that open for new users)
2. Revising the list of supported file extensions

I'll raise those and close this.
