### ISSUE TITLE
Different page formats in a single PDF (A4 portrait)

### ISSUE THREAD

**Issue by nicofrand** [travs/markdown-pdf#61]
Hi,

I am using the default settings I think, which means exporting in a PDF in portrait in A4.
However, while the export is fine, the format is not : there are different page format in the same output PDF as you can see here:

![atom-markdown-pdf](https://cloud.githubusercontent.com/assets/3419050/8207908/db16f1e4-1504-11e5-8c7d-0299256c4f95.png)

I am using tables in the second page (which seems larger than a standard  portrait), maybe it can help you ?

I'd prefer not to post here my mardown file but I can give it by email on request.

**Comment by travs** [comment]
Hmm, this is strange. I will put this in a milestone to have a look at. 

I know this is kind of old now, but what happens when you try different page sizes?

**Comment by nicofrand** [comment]
I tried A4, Letter, A5, Tabloid, and I always have the same issue.
I also tried in landscape and the issue remains (but is less visible).

BUT it seems that it only happens when using tables : only the pages including tables seem to be larger ! However, I have a case where the table is split between two pages (page 2 and 3) in a 3 pages document and only the second page is larger (whereas the table on the third page has the same columns).

As I said, I can provide a markdown file by email if needed.

**Comment by travs** [comment]
Hmmm, interesting. This *may* relate to #65 . I am about to update the phantomJS version used here, so we'll see if the problem persists in the next version.

**Comment by nicofrand** [comment]
Please tell when the phantomJS version will be updated and the new markdown-pdf package released so that I can check it.

**Comment by nicofrand** [comment]
Have you updated the phantomJS version yet ? I have the version 1.3.9.

**Comment by travs** [comment]
@nicofrand 
Updated phantomJS.

Going to close this but please reopen if it persists!

**Comment by nicofrand** [comment]
I Will probably. With the last updates I lost a lot of things (code in a
light background instead of dark) but the page format is not solved. I am
not sure from where it comes from (markdown-preview for the skin ?)

Le ven. 25 mars 2016 20:59, Travis Jacobs <notifications@github.com> a
écrit :

**Comment by travs** [comment]
@nicofrand 
Yeah, going forward I am going to use github-flavored markdown stylings as they would appear on github.com since it's far more stable (for now), and depends only on one stylesheet.

If anyone has a stylesheet for the dark theme let me know and I can implement it.

**Comment by nicofrand** [comment]
I still have this issue.

But since the last update I have a new one. Before I had a nice output looking like this:

![bug-markdown-pdf-before](https://cloud.githubusercontent.com/assets/3419050/14273906/4d85d3cc-fb0e-11e5-8bcf-529b459c923a.png)

And now it looks like this:

![bug-markdown-pdf](https://cloud.githubusercontent.com/assets/3419050/14273915/5a7d521c-fb0e-11e5-9684-b194e53d0dfd.png)

The text is bigger and therefore cut, not with a black background (I checked the Github checkbox though) and there is a hideous huge scrollbar.

I do not know if I should open an issue or edit something on my side or… ?
