### ISSUE TITLE
Error converting to image format:Check console  for more information

### ISSUE THREAD

**Issue by JesseEisen** [travs/markdown-pdf#63]
env: windows 7
In my markdown file, i never add a image to it.  so  when i execute the 'convert' command, it returns this error to me, how can i fix it?

**Comment by travs** [comment]
@JesseEisen Can you check the console for more information, and tell me what it says there?

**Comment by Gaoura** [comment]
How can I access to the console ? I'm new on Atom and I got the same error by trying to convert it.

**Comment by travs** [comment]
@Gaoura 
`View > Developer > open Developer Tools`

**Comment by Gaoura** [comment]
Okay here is my screenshot
![bug markdown pdf](https://cloud.githubusercontent.com/assets/5923601/8609459/b6d5c7bc-26a5-11e5-8732-e5fbef44444a.png)

**Comment by travs** [comment]
@Gaoura Thanks for the output. Can you paste the full input file over [here](http://hastebin.com/) so it can be tested?

Also, what OS are you on?

**Comment by Gaoura** [comment]
Okay it was just a file to test the conversion, so here it is : http://hastebin.com/ebavucaxew.md

I'm on Windows 7 Home Premium 64 bits

**Comment by connorvanelswyk** [comment]
I'm experiencing the same issue.

Running OS X Yosemite, Version 10.10.4 (14E46)

![screen shot 2015-07-16 at 1 48 10 pm](https://cloud.githubusercontent.com/assets/7100798/8730819/5606331a-2bc1-11e5-9399-0a0947528c83.png)

**Comment by travs** [comment]
@Gaoura @connorvanelswyk Thank you for the updates. I am about to update the phantomJS version, so let's see if anything changes. Re-download if you are able to, and let me know.

**Comment by Gaoura** [comment]
It still does the same error message D:

**Comment by nicofrand** [comment]
I had the same issue.
I then opened markdown-pdf settings set the export type to "png" and then to "pdf" again.
I tried again and the export worked this time.

Is it possible that the export type value was cleared during an update (updated to 1.3.9 a few days ago) and has to be manually set again ?

**Comment by jdkcn** [comment]
I got this error with fontconfig warning.

how can i fix it.

![screenshot from 2015-09-01 09 19 23](https://cloud.githubusercontent.com/assets/3855/9594211/b622769e-508a-11e5-85ba-c6648fd73016.png)

**Comment by travs** [comment]
Long time since last update, but I'm taking this project back under my wing again.

@nicofrand Thanks for that. For those who have this issue, try the fix @nicofrand mentioned above.

@Gaoura This has been several months, and I have done a major overhaul of the code in the meantime.
I will close this issue for now, but if it persists, by all means please open it again.

**Comment by connorvanelswyk** [comment]
Nicely done @travs, exports like a champ.
