### ISSUE TITLE
Support table styling similar to markdown-preview

### ISSUE THREAD

**Issue by larsenwork** [travs/markdown-pdf#65]
E.g. table cell padding, href text-decoration etc...any suggestions? I'd like to have the pdf in the same style as built in atom preview.

https://github.com/larsenwork/monoid/blob/master/Readme.md

![screen shot 2015-06-30 at 00 01 17](https://cloud.githubusercontent.com/assets/3859425/8419626/71c009d6-1ebb-11e5-950c-d36e30cfd6d5.png)
![screen shot 2015-06-30 at 00 01 04](https://cloud.githubusercontent.com/assets/3859425/8419627/71e59fe8-1ebb-11e5-8d7b-d3450b5d5f53.png)

**Comment by travs** [comment]
Hmm I see the difference here. I feel like this may have been raised before, but if not I'll add it to the list of feature requests.
Thanks!

**Comment by travs** [comment]
@larsenwork 

Let me know if this is still the case, since there have been major updates to the code recently.

**Comment by larsenwork** [comment]
@travs looks good, great job :+1:
