### ISSUE TITLE
Add metadata to PDF

### ISSUE THREAD

**Issue by DominicBoisvert** [travs/markdown-pdf#66]
The PDF file generated by markdown-pdf does not have any metadata (title, author, keyword, object/subject). Having the possibility to add and modify metadata is important.

**Comment by travs** [comment]
I think this is beyond the scope of this package, which simply aims to produce a pdf file with content from the markdown file.
In other words, metadata is not supported in github flavoured markdown, so it would require some weird configuration in this package to support it.
For anyone else coming to this issue, it's best to use a more advanced pdf command line tool or editor to achieve this.
