### ISSUE TITLE
Revise the list of supported file extensions

### ISSUE THREAD

**Issue by travs** [travs/markdown-pdf#69]
Originally, my intention was to mirror the list of supported file extensions from markdown-preview, but this (combined with insufficient error messages) has led to some confusion (see #60).

Maybe there is no reason to filter for extensions at all, and just naïvely assume that everything is markdown anyway.

Thoughts?

cc: @jrauschenbusch @hiroqli @Stoo0rmq

**Comment by jrauschenbusch** [comment]
Absolutely d'accord! There is no reason for filtering.

**Comment by travs** [comment]
Fixed!
