### ISSUE TITLE
Exported PDF doesn't match markdown-preview's style

### ISSUE THREAD

**Issue by pydolan** [travs/markdown-pdf#71]
I'm currently using the default Atom style (dark gray background, light gray text). My markdown-preview settings have the "use github style" enabled, and when I preview my markdown file, the view has a white background, black text, etc.  Unfortunately, the exported PDF using markdown-pdf has the dark gray background. 

Additionally, I tried modifying ~/.atom/styles.less to have the following CSS (while disabling markdown-preview's "use github style"):
~~~~css
.markdown-preview {
  font-size: 12px;
  background-color: white;
  color: black;
}
~~~~
With this, markdown-preview shows this new style, but exporting still shows my default dark-gray-background style.

**Comment by phlippieb** [comment]
+1
Ubuntu 14.04

**Comment by alfiepates** [comment]
>The output PDF will be styled according to your currently-active theme in Atom

Try changing the Atom theme? I agree that `markdown-pdf` needs a configurable stylesheet option. 

It'd be nice if it behaved like `pandoc`, using the default unless there's an alternative in the directory.
