### ISSUE TITLE
Links doesn't work in the pdf

### ISSUE THREAD

**Issue by haidaraM** [travs/markdown-pdf#75]
Hi,
If I include some links in my Markdown, in the PDF generated I can't click them. They appear in blue and underlined but I can do nothing.
Configuration :
Ubuntu 14.04 LTS
Atom 1.0.2 - UI theme : Atom Material - Syntax theme : Base16 tomorrow dark.

I changed the UI theme but it's doesn't work.
Thanks in advance.

**Comment by travs** [comment]
Closing. Duplicate of #15 #9 
Please do a cursory search before posting a new issue.

**Comment by haidaraM** [comment]
Oups. Sorry
