### ISSUE TITLE
markdown-pdf not working anymore (1.3.8)

### ISSUE THREAD

**Issue by spren9er** [travs/markdown-pdf#77]
1.3.7: pdf converting worked fine.
1.3.8: no matter what .md file, the converted pdf document is damaged and cannot be opened.

System: MacOS X 10.10.4, MacBook Pro Retina 13' 2015, Atom 1.0.4
Settings: A4, portrait, pdf, others: default

Built-in Atom packages (89)
├── about@1.0.1
├── archive-view@0.58.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.49.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.41.0
├── autocomplete-atom-api@0.9.2
├── autocomplete-css@0.10.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.19.0
├── autocomplete-snippets@1.7.1
├── autoflow@0.25.0
├── autosave@0.22.0
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@0.26.0
├── base16-tomorrow-light-theme@0.9.0
├── bookmarks@0.36.0
├── bracket-matcher@0.76.0
├── command-palette@0.36.0
├── deprecation-cop@0.54.0
├── dev-live-reload@0.46.0
├── encoding-selector@0.21.0
├── exception-reporting@0.36.0
├── find-and-replace@0.176.0
├── fuzzy-finder@0.87.0
├── git-diff@0.55.0
├── go-to-line@0.30.0
├── grammar-selector@0.47.0
├── image-view@0.54.0
├── incompatible-packages@0.24.1
├── keybinding-resolver@0.33.0
├── language-c@0.47.0
├── language-clojure@0.16.0
├── language-coffee-script@0.41.0
├── language-csharp@0.7.0
├── language-css@0.32.2
├── language-gfm@0.80.0
├── language-git@0.10.0
├── language-go@0.35.0
├── language-html@0.40.1
├── language-hyperlink@0.14.0
├── language-java@0.16.0
├── language-javascript@0.87.1
├── language-json@0.16.0
├── language-less@0.28.2
├── language-make@0.15.0
├── language-mustache@0.12.0
├── language-objective-c@0.15.0
├── language-perl@0.28.0
├── language-php@0.28.0
├── language-property-list@0.8.0
├── language-python@0.38.0
├── language-ruby@0.57.0
├── language-ruby-on-rails@0.22.0
├── language-sass@0.40.1
├── language-shellscript@0.15.0
├── language-source@0.9.0
├── language-sql@0.17.0
├── language-text@0.7.0
├── language-todo@0.26.0
├── language-toml@0.16.0
├── language-xml@0.32.0
├── language-yaml@0.24.0
├── link@0.30.0
├── markdown-preview@0.150.0
├── metrics@0.51.0
├── notifications@0.57.0
├── one-dark-syntax@1.1.0
├── one-dark-ui@1.0.2
├── one-light-syntax@1.1.0
├── one-light-ui@1.0.2
├── open-on-github@0.37.0
├── package-generator@0.40.0
├── release-notes@0.53.0
├── settings-view@0.212.0
├── snippets@0.95.0
├── solarized-dark-syntax@0.38.1
├── solarized-light-syntax@0.22.1
├── spell-check@0.59.0
├── status-bar@0.75.1
├── styleguide@0.44.0
├── symbols-view@0.100.0
├── tabs@0.82.0
├── timecop@0.31.0
├── tree-view@0.181.1
├── update-package-dependencies@0.10.0
├── welcome@0.29.0
├── whitespace@0.30.0
└── wrap-guide@0.35.0

/Users/spren9er/.atom/packages (6)
├── color-picker@2.0.11
├── file-icons@1.6.2
├── markdown-pdf@1.3.8
├── merge-conflicts@1.3.5
├── pigments@0.9.3
└── rails-snippets@1.13.0

**Comment by kowalgregy** [comment]
I've the same problem, following update to 1.3.8 markdown-pdf stopped working :(

**Comment by travs** [comment]
Ouch, I'll revert. If anyone wants to help out, check out #76 .

**Comment by travs** [comment]
Assuming the previous version worked for you, I've reverted. Please update to 1.3.9

Closing, but comment if you still have issues.
05b019dcff380ae82288aeeeaecc6f6e9033e818
