### ISSUE TITLE
Markdown export not working

### ISSUE THREAD

**Issue by ITler** [travs/markdown-pdf#78]
When using convert on `.md` file, a dialog box occurs saying:

    Error converting to image format. Check console for more information

I'm absolutely new to _Atom_. I did a fresh installation on Ubuntu14LTS 64bit this morning and only added _markdown-pdf_ as package, yet. Maybe I miss any OS related requirements, thus package's Readme does not address any requirements. I did not find the console, which is mentioned by the error message. Maybe this issue is related to #77 as I also have version 1.3.8 installed.

**Comment by travs** [comment]
Try updating to 1.3.9 and let me know what happens

**Comment by ITler** [comment]
confirmed working... Thank you

**Comment by travs** [comment]
@ITler No sweat, thanks for the report
