### ISSUE TITLE
Table headings are styled incorrectly

### ISSUE THREAD

**Issue by chalford** [travs/markdown-pdf#79]
When I have the One Dark theme selected, and I convert a Markdown file to PDF, the headings of tables are styled incorrectly, which makes them unreadable. With One Light selected, the tables are fine:

<img width="837" alt="screen shot 2015-08-12 at 15 38 00" src="https://cloud.githubusercontent.com/assets/965725/9226809/435ea984-4108-11e5-8861-10475d63433a.png">

<img width="818" alt="screen shot 2015-08-12 at 15 38 35" src="https://cloud.githubusercontent.com/assets/965725/9226812/49695dd8-4108-11e5-8d97-a4c5ae4a0d1d.png">

**Comment by travs** [comment]
Thank you for the report.

This may be related to #65, for which I have not yet seen a fix.

I feel like tables are something that need [tests](https://github.com/travs/markdown-pdf/issues/76), since there have been several issues for them now.

**Comment by travs** [comment]
@chalford 
Let me know if this is still the case, since there have been major updates to the code recently.
