### ISSUE TITLE
image is missing in exported pdf file

### ISSUE THREAD

**Issue by oldratlee** [travs/markdown-pdf#8]
for example:

```
![](https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png)
```

**Comment by travs** [comment]
Hey! Can you provide a screenshot? I'd just like to see your markdown vs the output.

Thanks for the report :bug:

**Comment by zmb3** [comment]
@travs It looks exactly like the screenshots originally reported in this issue.

![image](https://cloud.githubusercontent.com/assets/7527103/5664371/eaf7e3bc-971d-11e4-8897-d0e3c02e26c2.png)

**Comment by travs** [comment]
@zmb3 
Ok, the problem is to do with windows vs *nix URI schemes.

I am publishing a patch right now with a quick hack that *may* fix this, but don't get your hopes up.

If you or someone else with a windows box could update to `1.2.10` and give it a shot I would greatly appreciate it.

If it ends up being a no-go I'll go for the long fix and get this resolved once and for all :muscle:

**Comment by zmb3** [comment]
No such luck.  1.2.10 is showing the same behavior.

**Comment by travs** [comment]
I thought I knew what the issue was but now I'm not so sure...

Had a chance to try this on two windows machines today, and it worked fine for me on both Windows 7 and Windows 8.1, using the same version of Atom as you used (0.155.0). There seems to be no problem with URIs.

The only way I could get the same output as you was to point to a non-existent `.png`.

You certainly have a `.png` in that folder, so that isn't the problem.

I was using Windows 7 home edition service pack 1 to be precise; what are you using?

Also, try updating Atom to the [latest version](https://github.com/atom/atom/releases/latest) and see if it works. 

I'm really at a loss on this one :confused:

**Comment by zmb3** [comment]
Hmm..  I just tried 1.2.10 in Atom 0.169.0 on Windows 8.1 x64, and it seems to work fine!

This is not the setup that I was previously having trouble with.  That was Windows 7 Enterprise with Atom 0.155.0.  I'll give it another try on that PC on Monday with the latest version of Atom.

**Comment by loleg** [comment]
An easy workaround for this if you're using a web server to proxy the wiki is to rewrite the path, e.g. like this in nginx:
```
location ^~ /_edit/screenshots/  {
 rewrite ^/_edit(/.*)$ $1 last;
 root /opt/realms/wiki;
}
```

**Comment by DeastinY** [comment]
Hi, 
I right now have the exact same problem with Atom 1.8.0.
But the "file://" workaround doesn't work either. I simply cannot insert any image

**Comment by ebiken** [comment]
Same for me on environment below.
* Windows 10
* Atom 1.8.0
* markdown-pdf 1.5.0

PATH to the image is relative like this, and happens on all images.
`![図#2-ref](images/20_datastructures-02-ref.png)`

**Comment by andersab** [comment]
Same problem for me...
Windows 7 Pro 64-bit
Atom 1.13.0 ia32

**Comment by theguitarman92** [comment]
I am still having this problem

**Comment by 6l20** [comment]
Hi !
Same problem here too...
Windows 10 Pro 64 bit
Atom 1.9.9
markdown-pdf 1.5.0

**Comment by felixnext** [comment]
Same Problem!
Win 10 x64
Atom 1.15.0
markdown-pdf 1.5.0

**Comment by eddy-ojb** [comment]
Me too! Any solutions anybody?

**Comment by eddy-ojb** [comment]
Windows 10. Atom 1.16.0 x64. markdown pdf 1.5.0

**Comment by eddy-ojb** [comment]
Does this module use pandoc in anyway? My images are png's. They load fine in the preview don't convert to pdf. Pandoc preview of the document fails to load the images. I wonder if they're connected.

**Comment by markdrake** [comment]
I still have this problem, Windows 10. Atom 1.23.2 and markdown pdf 2.1.0

I get the preview correctly but generated pdf has no images at all (not even the alt is generated as a place holder), do we know how to make this work? 

Thanks in advance :)

**Comment by cmacdonnacha** [comment]
+1 any update on this?

**Comment by janjaapmeijer** [comment]
> Hi,
> I right now have the exact same problem with Atom 1.8.0 on Windows 8.1 x64.
> But the "file://" workaround doesn't work either. I simply cannot insert any image.
> In preview they are shown correctly, but the converted pdf does not contain them.

Try using the full path, but now without "file://" in front of it, that worked for me.
e.g. /home/username/images/fig.png instead of file:///home/username/images/fig.png

**Comment by scookies** [comment]
I tried as @janjaapmeijer suggested and it works.  But it's not ideal because I have my md file in github.  If I use full file path, it will not work for other people who fetch my repo.  I wish we can do it without giving full path.

**Comment by Mihier-Roy** [comment]
It works if you give a complete relative path to the picture.

E.g 
`![Picture](./assets/img1.png)`

This seems to work and the image is displayed in the PDF that is generated as well.

**Comment by SpecialMay** [comment]
In windows 10 , vscode , markdown
When it's
 `![pictrure](picture\gan_generated_image_epoch_80.png)`
I get the preview correctly but generated pdf has no images 
but when I use the `/`, like  `![pictrure](picture/gan_generated_image_epoch_80.png)`
it both works.

**Comment by luc4leone** [comment]
> It works if you give a complete relative path to the picture.

great tip, thanks!

**Comment by srbgupta** [comment]
Hi,
I am still not able to view images in the PDF. My md file is in a output folder that is parallel to project src folder.
and the images are under src/images/images_name.png.
when giving the path egs - 
`![](../src/images/plugins.png)`
the preview is available in VS Code but pdf is not displaying the image.
Using Windows 10, VSCode.

**Comment by sergio-nunez-meneses** [comment]
Hi everyone,

This path format worked for me for both the markdown preview, and the markdown to pdf package.

`![](../images/triangle-client-paas-server.png)`

Using Windows 10, Atom 1.53.0 x64

**Comment by jwamoney** [comment]
For anyone elses benefit that got stuck like me, I had folder structure:

`app\guide`

files in folder guide:
```
  user-guide.md
  login.png
```

I tried all sorts:

```
![Worked in Preview](login.png)
![Neither](./app/guide/login.png)
![Neither](/app/guide/login.png)
![Neither](.app/guide/login.png)
![Neither](app/guide/login.png)
![Worked in PDF](guide/login.png)
![Worked in Preview](/guide/login.png)
![Neither](.guide/login.png)
![Worked in PDF](./guide/login.png)
```

I was running the command in gitbash from the app folder:

`markdown-pdf guide/user-guide.md`

THEN I ran gitbash from the guide folder!

`markdown-pdf user-guide.md`

And then this worked in both (and github):
_also make sure that your file name isn't login.PNG... this will work in preview and pdf but not on github_

`![Praise the lord](login.png)`

Maybe I am just an idiot but hopefully this may help a random passer by.

Using Windows 10, Visual studio Code 1.52.1, markdown-pdf v10.0.0

**Comment by amasud08** [comment]
> Hi everyone,
> 
> This path format worked for me for both the markdown preview, and the markdown to pdf package.
> 
> `![](../images/triangle-client-paas-server.png)`
> 
> Using Windows 10, Atom 1.53.0 x64

me too! putting .. before the path did the job. Eg. ![image] (../graphs/activity_plot.png)

Thanks!

**Comment by kathy330** [comment]
I got the same problem, do you guys have any idea how to fix it?

**Comment by Skiddoh** [comment]
> > Hi everyone,
> > This path format worked for me for both the markdown preview, and the markdown to pdf package.
> > `![](../images/triangle-client-paas-server.png)`
> > Using Windows 10, Atom 1.53.0 x64
> 
> me too! putting .. before the path did the job. Eg. ![image] (../graphs/activity_plot.png)
> 
> Thanks!

for me it needed to be a single . as the images folder is on the same level, rather then on the folder level above.
thanks for your help!

**Comment by TrentuQuiyum** [comment]
> > Hi everyone,
> > This path format worked for me for both the markdown preview, and the markdown to pdf package.
> > `![](../images/triangle-client-paas-server.png)`
> > Using Windows 10, Atom 1.53.0 x64
> 
> me too! putting .. before the path did the job. Eg. ![image] (../graphs/activity_plot.png)
> 
> Thanks!

Putting .. before image path worked for me
Thanks
Was losing my mind over this
