### ISSUE TITLE
Improve User Feedback

### ISSUE THREAD

**Issue by towijo** [travs/markdown-pdf#81]
When executing "Markdown to PDF" the user must receive some feedback on weather or not the export was successful. Right now the user isn't receiving anything. It would be enough with some status message at the bottom:

**Markdown successfully converted: [Somefile.pdf](#)**

or if failed:

**Failed to convert markdown to PDF: [View Log](#)**

**Comment by travs** [comment]
I totally agree. Right now there is a message logged to the dev console, but that's not visible enough for most users.

**Comment by NKMR6194** [comment]
I think it is better to implement user feedback as soon as possible.

Not woring issue (#82) is reported but matter of it is not in package. Error is occured by user. 

>Yep, I see the error on it:
>
>>Please save the file as a markdown (.markdown, .md, .mkd, .mkdown or .ron)
>
>It was because the file was a .txt instead of .md.

If user see feedback, it can reduce such issues.

**Comment by travs** [comment]
@NKMR6194 You're right. I have *no* time to do this right now unfortunately, but can implement when I get around to it

**Comment by NKMR6194** [comment]
@travs 

May I implement it?
If I implement it, notifications will show message which is use by `console.log()`.
I will use https://github.com/atom/notifications which is atom api.

**Comment by travs** [comment]
Closed by #83
