### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by dumingxin** [travs/markdown-pdf#82]
the command  convert  doesn't work, no pdf file appear

**Comment by arall** [comment]
+1. 
After executing the command, nothing happens.

I'm using Atom 1.0.7 and OS X 10.10.4.

**Comment by NKMR6194** [comment]
???
Converting is successfully on my mac.
I can convert [README.md](https://github.com/travs/markdown-pdf/blob/master/README.md) to pdf.

OSX 10.10.5
Atom 1.0.7
markdown-pdf 1.3.9

Are there any log in `View >  Toggle Developer Tools > Console`?

**Comment by arall** [comment]
Yep, I see the error on it:

>Please save the file as a markdown (.markdown, .md, .mkd, .mkdown or .ron)

It was because the file was a `.txt` instead of `.md`.

This fixes my issue. @dumingxin maybe its also your case?

**Comment by NKMR6194** [comment]
@arall :+1:

**Comment by dumingxin** [comment]
It worked today.I don't know the reason
