### ISSUE TITLE
No word wrapping in code blocks.

### ISSUE THREAD

**Issue by synthecypher** [travs/markdown-pdf#85]
A word wrap option would be good or something.
![image](https://cloud.githubusercontent.com/assets/1833542/9732229/3b56d2e4-561a-11e5-9076-388fbfc82976.png)

**Comment by travs** [comment]
@synthecypher 
Major updates recently. 
Does this still occur?

**Comment by lukehsiao** [comment]
Using `markdown-pdf` version 1.5.0, this still occurs for me:

![image](https://cloud.githubusercontent.com/assets/7573542/14261503/b99712aa-fa65-11e5-8173-c6240cce2c78.png)

**Comment by eonist** [comment]
Still occurs. I guess if there was a way to force Atom to not wrap code blocks?

**Comment by jack6liu** [comment]
till now, still no word wrap in code blocks

**Comment by alexis-renard** [comment]
Still waiting for a support here, it's pretty anoying manually wrap the code :/

**Comment by vaughany** [comment]
Just to add my 2p, I'm also in a position where I have long code blocks which are disappearing off the right-hand side due to their length.

**Comment by travs** [comment]
duplicate of #21; please refer to that issue. Also will be looking for a fix for this in the next little while

**Comment by skofgar** [comment]
This problem is still happening for me. I don't see a scrollbar, but code doesn't wrap and just goes off the screen.

**Comment by danieltaylor** [comment]
@skofgar Same here.  Adding `  white-space: pre-wrap;` to the `.markdown-body pre code { ... }` block in `markdown-pdf/node_modules/mdpdf/src/assets/github-markdown-css.css` as suggested [here](https://github.com/travs/markdown-pdf/issues/21#issuecomment-392895273) fixed the issue for me.
