### ISSUE TITLE
Emoji are not exported

### ISSUE THREAD

**Issue by nbarbettini** [travs/markdown-pdf#86]
I have a markdown document with some emoji, like:

```
Give it a try! :smile:
```

[Markdown Preview](https://github.com/atom/markdown-preview) renders this correctly as :smile: , but the PDF just includes an empty square.

**Comment by James-Firth** [comment]
Noticed this today and would appreciate if they were embedded properly.
I assume the emoji font simply needs to be embedded in the PDF?

**Comment by nbarbettini** [comment]
A lot of modern OS have support for emoji without needing additional fonts. I'm not sure how it would work inside a PDF document, though.

**Comment by travs** [comment]
Good catch :+1:
Going to tag this as an enhancement. 
If there's enough demand for this I will implement (short on time right now).
PRs are always welcome :wink:

**Comment by eivindml** [comment]
Would also love this! Not sure why the converter not just pushes the unicode characters through to the PDF file, so they would be dispayed by the OS?

**Comment by travs** [comment]
Have changed the default renderer to `mdpdf`, which supports emoji out of the box. Closing this one now.
