### ISSUE TITLE
Enable selectable text in PDF output on OS X

### ISSUE THREAD

**Issue by travs** [travs/markdown-pdf#9]
This is due to the way PhantomJS renders the PDF, but is not a problem on other operating systems apparently.

Since this is out of our direct control, we can wait until the feature is supported, then just update the dependency. 

[The issue is being tracked here](https://github.com/ariya/phantomjs/issues/10196).

**Comment by CremboC** [comment]
Any update on this?

**Comment by travs** [comment]
@CremboC Unfortunately I left this package for quite a while, but now I'm finally back. 

This may already be fixed when we update the dependencies this package uses, as that's how the PDF is actually rendered.

**Comment by travs** [comment]
@CremboC @beltex 
This issue is fixed now, at least on Windows 7 and OS X Mavericks (haven't tested on linux).

**Comment by beltex** [comment]
Great, thanks @travs! :) Can confirm that it works on OS X El Capitan.
