### ISSUE TITLE
No render in GitHub.com style since last update

### ISSUE THREAD

**Issue by whizzo** [travs/markdown-pdf#93]
Since I update:

- atom 1.1.0
- markdown-preview 0.154.0

...in my Arch Linux x64 system, markdown-pdf doesn't render with GitHub.com style, it uses Syntax Theme I have in configuration, although I have GitHub.com style checked in my markdown-preview configuration.

Same configuration with earlier version works perfectly.

Sorry about my bad english.

**Comment by Leeds-eBooks** [comment]
:+1:  Not sure whose responsibility it is to fix this – there's this issue on the markdown-preview package https://github.com/atom/markdown-preview/issues/322

**Comment by travs** [comment]
This should be fixed by recent updates; reopen if necessary
