### ISSUE TITLE
Table header duplicated and overlapping when starting on new page

### ISSUE THREAD

**Issue by mlda065** [travs/markdown-pdf#95]
When a table starts at the top of a new page (not the first page), the header row is duplicated, and the two copies overlap each other.

![problem screenshop](https://cloud.githubusercontent.com/assets/7035647/11737649/8561aaa8-a02f-11e5-9f76-9560d6467284.png)

If I add a sentence to the top of that page (so the table is not the first thing on that page) then the problem goes away.

![all good again](https://cloud.githubusercontent.com/assets/7035647/11737662/b92f24d2-a02f-11e5-838d-aca30766d409.png)

I suspect this is caused by a bug in the functionality which re-states the header when a table spans across a page break.

i.e.

![screenshot from 2015-12-11 17 49 42](https://cloud.githubusercontent.com/assets/7035647/11737655/973f55cc-a02f-11e5-9b02-772204ea51da.png)

Here's the code I'm using.

(The `<font...` stuff is because otherwise we get a black font on a black background. That's already raised as [a different bug](https://github.com/travs/markdown-pdf/issues/79). This header duplication happens even without that font colour change.)

    words words words

    words words words

    words words words

    words words words

    words words words

    words words words

    words words words

    words words words

    words words

    words words words

    words words words

    words words words

    words words words

    words words words

    words words words

    words words

    words words words

    words words words

    words words words

    words words words

    words words words

    words words words

    words words words

    | <font color='white'>Tables</font>   |      <font color='white'>Tables</font>      |  <font color='white'>Tables</font> |
    |----------|:-------------:|------:|
    | col 1 is |  left-aligned | $1600 |
    | col 2 is |    centered   |   $12 |
    | col 3 is | right-aligned |    $1 |

**Comment by travs** [comment]
Let me know if this is still the case, since there have been major updates to the code recently.

**Comment by mlda065** [comment]
Yep, it looks fine now.
