### ISSUE TITLE
hyperlinks not exported.

### ISSUE THREAD

**Issue by koolhead17** [travs/markdown-pdf#96]
Hi,
Thanks for the plugin, wanted to know if in process of markdown to PDF conversion does it supports embedded hyperlinks? I just did a convert & it has some web URLs embedded in markdown which i have not been able to see as hyperlink in my pdf.

Thanks again.

**Comment by travs** [comment]
Assuming this is similar to #9 (and the issues linked there), it should be fixed now.
Reopen if the new version doesn't fix it.
