### ISSUE TITLE
Nothing happened after clicking `convert`

### ISSUE THREAD

**Issue by shenwei356** [travs/markdown-pdf#97]
Nothing happened after clicking `convert`

**Comment by aautio** [comment]
How did you solve this?

**Comment by shenwei356** [comment]
@aautio using `npm` to install `html-pdf` and `marked ` with root privilege. 

by the way, gfm-pdf is more easy to install and with a better looking.

**Comment by aautio** [comment]
@shenwei356 ok, thanks!
