### ISSUE TITLE
Not converting files

### ISSUE THREAD

**Issue by torkelrogstad** [travs/markdown-pdf#98]
Hi!

Upon trying to convert a file with .md-suffix I get the error 

`TypeError: Cannot read property 'mainModule' of undefined(…)`

at 

`
/Users/xxx/.atom/packages/markdown-pdf/lib/markdown-pdf.js:74
`

This is the first issue I'm opening ever, so I have no idea if I have provided sufficient information.

**Comment by jjloneman** [comment]
I just spent an hour trying to figure out this issue myself.

Line 4 of the `markdown-pdf.js` has this line:
`var mdpreview = atom.packages.activePackages["markdown-preview"];`
which gets contents from the package `markdown-preview`.

Long story short, if you installed another package like `markdown-preview-plus`, it most likely disabled `markdown-preview`. If you go to `File > Settings > Packages` and find `markdown-preview`, make sure it's enabled.

I think there needs to be a check in the code to make sure the package is enabled.

**Comment by rolfpancake** [comment]
Thanks for the tip @jjloneman.
This should be documented somewhere.

**Comment by travs** [comment]
This should be fixed now, and an error should pop up if there is no preview available!
