### ISSUE TITLE
Adding an option to use another theme as it's output theme

### ISSUE THREAD

**Issue by Saucy** [travs/markdown-pdf#99]
I use a dark theme in Atom, but I'd like to use another theme for the PDF output. I couldn't find any issues with this topic btw.

It's a very minor feature. Maybe a dropdown list with all the available Atom themes you could choose to output as? (I don't know if Atom packages can access the list of Atom themes?)

I hope I've made myself clear, ask otherwise!

_**Edit:** How can I make it ignore my current theme and only use markdown-preview theme (white background, blue links, etc)?_

**Comment by travs** [comment]
I think this is fixed now, if I understand the edit correctly, since the only output is now github-flavored markdown, similar to what is rendered on github.
